<?php

namespace Database\Seeders;

use App\Models\CriseHistorica;
use Illuminate\Database\Seeder;

class CrisesHistoricasSeeder extends Seeder
{
    public function run(): void
    {
        $crises = [
            [
                'titulo'              => 'Dissolução da URSS',
                'slug'                => 'dissolucao-da-urss',
                'ano'                 => 1991,
                'data_inicio'         => '1991-08-19',
                'data_fim'            => '1991-12-26',
                'contexto_geopolitico' => 'A dissolução da União das Repúblicas Socialistas Soviéticas representou o fim da Guerra Fria e o colapso de um dos dois grandes blocos de poder do século XX. Após décadas de corrida armamentista e confronto ideológico com o Ocidente, a URSS enfrentou uma profunda crise interna alimentada por fracassos econômicos, movimentos nacionalistas nas repúblicas periféricas e a política de glasnost e perestroika de Mikhail Gorbachev. A tentativa de golpe em agosto de 1991 por setores conservadores acelerou o processo de desintegração. Em dezembro de 1991, os líderes da Rússia, Ucrânia e Bielorrússia assinaram o Acordo de Belavezha, extinguindo formalmente a URSS e criando a Comunidade dos Estados Independentes. O evento redesenhou completamente o mapa político do leste europeu e da Ásia Central, dando origem a 15 novos Estados soberanos.',
                'impacto_global'      => 'O fim da URSS transformou a ordem mundial bipolar em um sistema unipolar temporário liderado pelos Estados Unidos. A expansão da OTAN para o leste, a transição para economias de mercado nos países do ex-bloco soviético e a proliferação nuclear tornaram-se preocupações centrais da nova geopolítica global. Dezenas de conflitos étnicos e regionais eclodiram nas antigas repúblicas soviéticas, redefinindo fronteiras e identidades nacionais na Europa Oriental e Ásia Central.',
                'impacto_brasil'      => 'O Brasil aproveitou o fim do confronto ideológico para aprofundar sua política externa independente e diversificar parcerias comerciais. A abertura econômica da década de 1990 foi parcialmente influenciada pelo consenso neoliberal que emergiu após a vitória do capitalismo na Guerra Fria. O país passou a negociar diretamente com as novas repúblicas ex-soviéticas, especialmente na área de agronegócio.',
                'metricas_globais'    => [
                    ['indicador' => 'Repúblicas independentes criadas', 'valor' => 15, 'unidade' => 'países'],
                    ['indicador' => 'Redução do arsenal nuclear soviético herdado', 'valor' => 27000, 'unidade' => 'ogivas nucleares'],
                ],
                'metricas_brasil'     => [
                    ['indicador' => 'Crescimento das exportações ao Leste Europeu (1992-1995)', 'valor' => 34, 'unidade' => '%'],
                ],
                'categorias'          => ['geopolítica', 'transição'],
                'content_slug'        => null,
            ],
            [
                'titulo'              => 'Guerra do Golfo',
                'slug'                => 'guerra-do-golfo',
                'ano'                 => 1991,
                'data_inicio'         => '1990-08-02',
                'data_fim'            => '1991-02-28',
                'contexto_geopolitico' => 'A Guerra do Golfo foi desencadeada pela invasão iraquiana do Kuwait em agosto de 1990, ordenada por Saddam Hussein sob pretexto de disputas territoriais e acusações de extração excessiva de petróleo do campo de Rumaila. A comunidade internacional, liderada pelos Estados Unidos, reagiu com uma série de resoluções do Conselho de Segurança da ONU impondo sanções e autorizando o uso da força. Uma coalizão de 35 países enviou forças ao Oriente Médio na Operação Escudo do Deserto, convertida em Tempestade do Deserto em janeiro de 1991. A guerra foi marcada pelo uso massivo de tecnologia militar avançada e transmitida ao vivo pela CNN, inaugurando uma nova era de cobertura midiática de conflitos. A rápida derrota iraquiana em apenas 100 horas de combate terrestre evidenciou a superioridade militar americana no pós-Guerra Fria.',
                'impacto_global'      => 'A guerra solidificou a presença militar americana no Oriente Médio e estabeleceu novas normas de intervenção humanitária respaldada pela ONU. Os preços do petróleo sofreram volatilidade extrema, impactando economias globais. O Iraque foi submetido a décadas de sanções internacionais. O conflito também evidenciou as tensões entre soberania nacional e intervenção internacional, tema que moldaria a política externa global nas décadas seguintes.',
                'impacto_brasil'      => 'O choque do petróleo impactou a balança de pagamentos brasileira, pressionando a inflação já elevada no período. O Brasil, então em transição democrática, apoiou as resoluções da ONU mas não enviou tropas combatentes. O conflito acelerou discussões sobre a dependência energética nacional e reforçou investimentos na Petrobras.',
                'metricas_globais'    => [
                    ['indicador' => 'Países na coalizão', 'valor' => 35, 'unidade' => 'países'],
                    ['indicador' => 'Pico do preço do barril de petróleo', 'valor' => 46, 'unidade' => 'USD/barril'],
                ],
                'metricas_brasil'     => [
                    ['indicador' => 'Variação da inflação no período (IGP-M)', 'valor' => 458, 'unidade' => '% ao ano (1991)'],
                ],
                'categorias'          => ['guerra', 'petróleo'],
                'content_slug'        => null,
            ],
            [
                'titulo'              => 'Genocídio em Ruanda',
                'slug'                => 'genocidio-em-ruanda',
                'ano'                 => 1994,
                'data_inicio'         => '1994-04-07',
                'data_fim'            => '1994-07-15',
                'contexto_geopolitico' => 'O genocídio de Ruanda foi um dos eventos mais sangrentos da história contemporânea, resultando no assassinato de aproximadamente 800 mil pessoas, majoritariamente da etnia tutsi, em cerca de 100 dias. O conflito tinha raízes profundas nas divisões étnicas criadas e amplificadas pelo colonialismo belga, que transformou distinções sociais em categorias raciais rígidas. O assassinato do presidente Juvénal Habyarimana em 6 de abril de 1994 serviu como estopim para a violência sistemática organizada pelos extremistas hutu do governo e a milícia Interahamwe. A comunidade internacional, incluindo as forças da ONU presentes no país, foi acusada de omissão e inação diante do massacre. O genocídio terminou com a vitória militar da Frente Patriótica Ruandesa liderada por Paul Kagame, que assumiu o controle do país e iniciou um processo complexo de reconstrução nacional.',
                'impacto_global'      => 'O genocídio ruandês expôs as limitações da comunidade internacional e gerou profundas revisões na doutrina da Responsabilidade de Proteger (R2P). A ONU foi duramente criticada pela inação de suas forças locais. O evento impulsionou debates sobre intervenção humanitária, tribunais internacionais e prevenção de genocídios, levando à criação do Tribunal Penal Internacional para Ruanda e influenciando a criação do TPI permanente em 2002.',
                'impacto_brasil'      => 'O Brasil não tinha presença significativa na região, mas o evento influenciou a política externa brasileira em debates sobre soberania versus intervenção humanitária. O país participou posteriormente de missões de paz da ONU na África, inspirado em parte pela lição de Ruanda sobre os custos da omissão internacional.',
                'metricas_globais'    => [
                    ['indicador' => 'Estimativa de vítimas fatais', 'valor' => 800000, 'unidade' => 'pessoas'],
                    ['indicador' => 'Duração do genocídio', 'valor' => 100, 'unidade' => 'dias'],
                ],
                'metricas_brasil'     => [
                    ['indicador' => 'Militares brasileiros em missões ONU na África (anos 2000)', 'valor' => 1200, 'unidade' => 'soldados'],
                ],
                'categorias'          => ['humanitária', 'guerra'],
                'content_slug'        => null,
            ],
            [
                'titulo'              => 'Guerra da Bósnia',
                'slug'                => 'guerra-da-bosnia',
                'ano'                 => 1992,
                'data_inicio'         => '1992-04-06',
                'data_fim'            => '1995-12-14',
                'contexto_geopolitico' => 'A Guerra da Bósnia resultou da desintegração da Iugoslávia e da declaração de independência da Bósnia-Herzegovina em março de 1992. O conflito envolveu três grupos étnicos principais — bósnios muçulmanos (bósniacos), sérvios bósnios e croatas bósnios — em uma guerra de extrema crueldade marcada por limpeza étnica, campos de concentração e o cerco de Sarajevo, o mais longo da história da guerra moderna. As forças sérvias bósnias, apoiadas pela Sérvia, cometeram o massacre de Srebrenica em julho de 1995, considerado o maior genocídio na Europa desde a Segunda Guerra Mundial. A inação inicial da comunidade internacional e as falhas da UNPROFOR geraram enorme pressão para uma intervenção mais efetiva. Os Acordos de Dayton, assinados em novembro de 1995, encerraram formalmente o conflito e dividiram a Bósnia em duas entidades políticas.',
                'impacto_global'      => 'A guerra expôs as limitações da Europa pós-Guerra Fria em lidar com conflitos regionais e forçou uma redefinição do papel da OTAN. O massacre de Srebrenica levou à criação do Tribunal Penal Internacional para a ex-Iugoslávia. O conflito também acelerou o processo de integração europeia e a expansão da OTAN como mecanismos de estabilização, moldando a arquitetura de segurança europeia por décadas.',
                'impacto_brasil'      => 'O Brasil contribuiu com forças para a missão de paz UNPROFOR e apoiou os esforços diplomáticos nos foros multilaterais. O conflito reforçou a posição brasileira de defesa do direito internacional e da mediação diplomática. A crise também gerou debates internos sobre o papel do Brasil em operações de paz, preparando o país para missões mais robustas como a MINUSTAH no Haiti.',
                'metricas_globais'    => [
                    ['indicador' => 'Mortos no conflito', 'valor' => 100000, 'unidade' => 'pessoas'],
                    ['indicador' => 'Refugiados e deslocados', 'valor' => 2200000, 'unidade' => 'pessoas'],
                ],
                'metricas_brasil'     => [
                    ['indicador' => 'Militares brasileiros na UNPROFOR', 'valor' => 80, 'unidade' => 'soldados'],
                ],
                'categorias'          => ['guerra', 'humanitária'],
                'content_slug'        => null,
            ],
            [
                'titulo'              => 'Crise Financeira Asiática',
                'slug'                => 'crise-financeira-asiatica',
                'ano'                 => 1997,
                'data_inicio'         => '1997-07-02',
                'data_fim'            => '1998-12-31',
                'contexto_geopolitico' => 'A Crise Financeira Asiática eclodiu em julho de 1997 com a desvalorização do baht tailandês após o colapso de bolhas especulativas no setor imobiliário e nas bolsas de valores. O contágio rapidamente se espalhou para a Indonésia, Malásia, Coreia do Sul, Filipinas e Hong Kong, revelando vulnerabilidades estruturais dessas economias: déficits em conta corrente elevados, elevada dívida de curto prazo em moeda estrangeira, sistemas bancários frágeis e regimes de câmbio fixo insustentáveis. O FMI interveio com pacotes de socorro condicionados a reformas estruturais que aprofundaram a recessão em vários países. A crise derrubou governos, incluindo o de Suharto na Indonésia após 32 anos no poder, e gerou distúrbios sociais graves. A recuperação variou entre os países, com Coreia do Sul e Malásia se reerguendo mais rapidamente através de diferentes abordagens políticas.',
                'impacto_global'      => 'A crise asiática abalou a confiança no modelo de desenvolvimento dos "Tigres Asiáticos" e expôs riscos do capitalismo financeiro globalizado. Gerou revisões na arquitetura financeira internacional, fortaleceu debates sobre controle de capitais e levou à criação de mecanismos regionais de defesa como a Iniciativa de Chiang Mai. A crise também acelerou a ascensão da China como potência econômica alternativa ao modelo liberalizante do FMI.',
                'impacto_brasil'      => 'O Brasil sofreu forte pressão especulativa sobre o real, levando a uma elevação drástica das taxas de juros pelo Banco Central. A crise acelerou a deterioração das contas externas brasileiras e foi um dos fatores que levaram à desvalorização cambial de janeiro de 1999. O governo FHC foi forçado a negociar um acordo preventivo com o FMI ainda em 1998.',
                'metricas_globais'    => [
                    ['indicador' => 'Queda do PIB da Indonésia em 1998', 'valor' => -13.1, 'unidade' => '%'],
                    ['indicador' => 'Pacote de socorro FMI à Coreia do Sul', 'valor' => 57, 'unidade' => 'bilhões USD'],
                ],
                'metricas_brasil'     => [
                    ['indicador' => 'Taxa Selic no pico da crise (1997)', 'valor' => 43, 'unidade' => '% ao ano'],
                ],
                'categorias'          => ['econômica', 'financeira'],
                'content_slug'        => null,
            ],
            [
                'titulo'              => 'Crise Financeira Russa',
                'slug'                => 'crise-financeira-russa',
                'ano'                 => 1998,
                'data_inicio'         => '1998-08-17',
                'data_fim'            => '1999-06-30',
                'contexto_geopolitico' => 'A crise financeira russa de 1998 foi desencadeada por uma combinação de fatores: herança da transição caótica do comunismo para o capitalismo, queda abrupta nos preços do petróleo e do gás natural, contágio da crise asiática, elevada dívida pública de curto prazo e uma estrutura de pirâmide financeira nos títulos públicos (GKOs). Em agosto de 1998, o governo russo declarou moratória sobre parte de sua dívida interna e desvalorizou o rublo, que perdeu dois terços de seu valor em poucas semanas. A crise derrubou o governo de Sergei Kiriyenko e provocou uma grave contração econômica. O FMI havia concedido um pacote de socorro de US$ 22,6 bilhões meses antes, mas as reservas foram rapidamente esgotadas. A crise teve repercussões internacionais severas, incluindo o colapso do fundo LTCM nos EUA, que exigiu resgate emergencial do Federal Reserve.',
                'impacto_global'      => 'A crise russa demonstrou os riscos sistêmicos da integração financeira global e contribuiu para o colapso do LTCM, ameaçando a estabilidade do sistema financeiro americano. O evento fortaleceu correntes críticas ao Consenso de Washington e ao modelo de transição rápida para o capitalismo. A recuperação posterior da Rússia, favorecida pela alta do petróleo, lançou as bases para o retorno russo como potência geopolítica sob Putin.',
                'impacto_brasil'      => 'A crise russa foi o golpe final sobre o real sobrevalorizado. O contágio levou o Brasil a negociar um acordo com o FMI de US$ 41,5 bilhões em novembro de 1998 e, ainda assim, forçou a desvalorização cambial em janeiro de 1999. A crise expôs a vulnerabilidade do Plano Real ao câmbio fixo e forçou uma mudança de regime monetário para câmbio flutuante com metas de inflação.',
                'metricas_globais'    => [
                    ['indicador' => 'Desvalorização do rublo', 'valor' => -66, 'unidade' => '%'],
                    ['indicador' => 'Queda do PIB russo em 1998', 'valor' => -5.3, 'unidade' => '%'],
                ],
                'metricas_brasil'     => [
                    ['indicador' => 'Fuga de capitais do Brasil (agosto-dezembro 1998)', 'valor' => 30, 'unidade' => 'bilhões USD'],
                ],
                'categorias'          => ['econômica', 'financeira'],
                'content_slug'        => null,
            ],
            [
                'titulo'              => 'Atentados de 11 de Setembro',
                'slug'                => 'atentados-de-11-de-setembro',
                'ano'                 => 2001,
                'data_inicio'         => '2001-09-11',
                'data_fim'            => '2001-09-11',
                'contexto_geopolitico' => 'Os atentados de 11 de setembro de 2001 foram uma série de ataques terroristas coordenados pela rede Al-Qaeda contra os Estados Unidos, utilizando quatro aeronaves comerciais sequestradas. As Torres Gêmeas do World Trade Center em Nova York foram destruídas, o Pentágono foi parcialmente atingido e um quarto avião caiu na Pensilvânia após reação dos passageiros. Quase três mil pessoas morreram nos ataques. O evento chocou o mundo por sua escala sem precedentes e transformou radicalmente a política de segurança global. O governo Bush declarou a "Guerra ao Terror" e invocou o Artigo 5 da OTAN pela primeira vez na história, obtendo apoio internacional para operações militares. Osama bin Laden e a Al-Qaeda reivindicaram os ataques, motivados por oposição à presença militar americana no Oriente Médio e apoio dos EUA a Israel. Os atentados geraram uma resposta militar que redefiniu a política externa americana por duas décadas.',
                'impacto_global'      => 'Os atentados de 11 de setembro reorientaram completamente a política externa americana e global em torno da "Guerra ao Terror". Geraram invasões do Afeganistão e Iraque, transformaram práticas de inteligência e vigilância, restringiram liberdades civis em nome da segurança e criaram novas arquiteturas de cooperação antiterrorismo. O impacto econômico imediato incluiu colapso temporário dos mercados financeiros, crise da aviação e seguros, com perdas estimadas em mais de US$ 2 trilhões ao longo dos conflitos subsequentes.',
                'impacto_brasil'      => 'O Brasil expressou solidariedade imediata aos EUA e apoiou resoluções da ONU autorizando ação militar no Afeganistão. O choque sobre os mercados financeiros globais afetou negativamente a economia brasileira, já fragilizada pela crise de 2001. O evento intensificou a cooperação em inteligência e segurança entre Brasil e EUA, e influenciou a criação de legislação antiterrorismo no país.',
                'metricas_globais'    => [
                    ['indicador' => 'Vítimas fatais', 'valor' => 2977, 'unidade' => 'pessoas'],
                    ['indicador' => 'Custo total das guerras subsequentes (estimado)', 'valor' => 8000, 'unidade' => 'bilhões USD'],
                ],
                'metricas_brasil'     => [
                    ['indicador' => 'Queda do Ibovespa na semana seguinte', 'valor' => -9.7, 'unidade' => '%'],
                ],
                'categorias'          => ['terrorismo', 'geopolítica'],
                'content_slug'        => null,
            ],
            [
                'titulo'              => 'Guerra do Afeganistão',
                'slug'                => 'guerra-do-afeganistao',
                'ano'                 => 2001,
                'data_inicio'         => '2001-10-07',
                'data_fim'            => '2021-08-30',
                'contexto_geopolitico' => 'A Guerra do Afeganistão foi desencadeada pelos atentados de 11 de setembro de 2001, quando os Estados Unidos e aliados da OTAN invadiram o país para derrubar o regime Talibã que abrigava a Al-Qaeda. A fase inicial da operação foi rápida: o regime Talibã foi derrubado em semanas. Porém, o conflito se prolongou por 20 anos, tornando-se a guerra mais longa da história americana. A construção estatal fracassou em criar instituições duráveis e combater a corrupção endêmica. O Talibã se reorganizou como insurgência, enquanto os EUA e aliados tentavam treinar forças de segurança afegãs e reconstruir o país. O custo humano e financeiro crescente gerou pressão doméstica nos EUA por retirada. Em 2021, o presidente Biden anunciou a retirada total, e o Talibã retomou o poder em agosto de 2021, antes mesmo da retirada ser concluída, num dos maiores fracassos da política externa americana.',
                'impacto_global'      => 'A guerra do Afeganistão mostrou os limites do poder militar americano na construção de Estados e demonstrou a resiliência de movimentos insurgentes com suporte populacional e regional. O fracasso deixou legados de instabilidade regional, crise de refugiados, retorno do Talibã ao poder e questionamentos sobre a estratégia ocidental de nation-building. A retirada caótica de 2021 impactou a credibilidade americana como aliado confiável.',
                'impacto_brasil'      => 'O Brasil não participou militarmente do conflito, mas a guerra afetou rotas comerciais, preços de commodities e dinâmicas geopolíticas que influenciaram a política externa brasileira. O longo conflito gerou debates no Itamaraty sobre os limites da intervenção militar e reforçou a posição brasileira de não intervenção e solução diplomática de conflitos.',
                'metricas_globais'    => [
                    ['indicador' => 'Duração do conflito', 'valor' => 20, 'unidade' => 'anos'],
                    ['indicador' => 'Custo total para os EUA', 'valor' => 2313, 'unidade' => 'bilhões USD'],
                ],
                'metricas_brasil'     => [
                    ['indicador' => 'Refugiados afegãos acolhidos pelo Brasil (2001-2021)', 'valor' => 320, 'unidade' => 'pessoas'],
                ],
                'categorias'          => ['guerra', 'terrorismo'],
                'content_slug'        => null,
            ],
            [
                'titulo'              => 'Guerra do Iraque',
                'slug'                => 'guerra-do-iraque',
                'ano'                 => 2003,
                'data_inicio'         => '2003-03-20',
                'data_fim'            => '2011-12-18',
                'contexto_geopolitico' => 'A Guerra do Iraque foi iniciada por uma coalizão liderada pelos Estados Unidos sob o governo Bush, com base em alegações — posteriormente desmentidas — de que o Iraque possuía armas de destruição em massa e tinha ligações com a Al-Qaeda. A invasão foi realizada sem autorização explícita do Conselho de Segurança da ONU, gerando profundas divisões na comunidade internacional, incluindo a oposição de França, Alemanha e Rússia. O regime de Saddam Hussein foi derrubado em três semanas, mas a ocupação mergulhou em uma insurgência violenta e numa guerra sectária entre sunitas, xiitas e curdos. A dissolução do exército iraquiano e o processo de desbathificação criaram um vácuo de segurança que favoreceu o surgimento de grupos jihadistas, incluindo a Al-Qaeda no Iraque, precursora do Estado Islâmico. A guerra gerou debates sobre o uso do poder militar, soberania nacional e legalidade das guerras preventivas.',
                'impacto_global'      => 'A guerra do Iraque dividiu profundamente o Ocidente, enfraqueceu a credibilidade americana e a autoridade das instituições internacionais. Os preços do petróleo dispararam e a instabilidade regional aumentou dramaticamente. A destruição do Estado iraquiano criou um ambiente propício para o extremismo e gerou o contexto para o surgimento do Estado Islâmico uma década depois. O conflito também redefiniu limites sobre intervenção unilateral e legitimidade do uso da força.',
                'impacto_brasil'      => 'O Brasil, sob o governo Lula, opôs-se veementemente à guerra, reforçando sua postura soberanista e multilateralista. O conflito elevou os preços do petróleo, beneficiando a Petrobras e contribuindo para o boom das commodities que impulsionou a economia brasileira nos anos 2000. Diplomaticamente, o Brasil ganhou prestígio junto a países em desenvolvimento por sua posição contrária à invasão.',
                'metricas_globais'    => [
                    ['indicador' => 'Mortos iraquianos civis e militares (estimativa)', 'valor' => 200000, 'unidade' => 'pessoas'],
                    ['indicador' => 'Custo total para os EUA', 'valor' => 1922, 'unidade' => 'bilhões USD'],
                ],
                'metricas_brasil'     => [
                    ['indicador' => 'Variação do preço do petróleo Brent (2003-2008)', 'valor' => 340, 'unidade' => '% de alta'],
                ],
                'categorias'          => ['guerra', 'petróleo'],
                'content_slug'        => null,
            ],
            [
                'titulo'              => 'Crise Financeira Global 2008',
                'slug'                => 'crise-financeira-global-2008',
                'ano'                 => 2008,
                'data_inicio'         => '2008-09-15',
                'data_fim'            => '2009-12-31',
                'contexto_geopolitico' => 'A Crise Financeira Global de 2008 foi desencadeada pelo colapso do mercado imobiliário americano, impulsionado por décadas de desregulação financeira, empréstimos hipotecários subprime irresponsáveis e a proliferação de derivativos financeiros complexos (CDOs, CDSs). A falência do Lehman Brothers em 15 de setembro de 2008 transformou uma crise de crédito em pânico financeiro global. O sistema bancário mundial ficou à beira do colapso, exigindo intervenções estatais sem precedentes: resgates bancários, injeções de liquidez pelos bancos centrais e pacotes de estímulo fiscal massivos. A crise revelou a interdependência do sistema financeiro global e os riscos sistêmicos criados pela inovação financeira desregulada. A Grande Recessão que se seguiu foi a maior contração econômica global desde a Grande Depressão dos anos 1930.',
                'impacto_global'      => 'A crise de 2008 redesenhou a ordem econômica global, elevando o G20 como principal fórum de coordenação econômica internacional e acelerando a ascensão da China. Levou à maior onda de regulação financeira desde os anos 1930, incluindo o Dodd-Frank nos EUA e Basileia III globalmente. O desemprego disparou na Europa e EUA, alimentando populismos e movimentos anti-establishment. A crise também gerou anos de políticas de juros zero e quantitative easing que transformaram os mercados de capitais globais.',
                'impacto_brasil'      => 'O Brasil atravessou a crise com relativa resiliência graças às reservas internacionais acumuladas, ao boom de commodities e à robustez do sistema bancário. O PIB contraiu apenas 0,1% em 2009, recuperando-se rapidamente em 2010 com crescimento de 7,5%. O país se tornou símbolo de emergência econômica bem-sucedida, e Lula declarou que a crise era "problema de gente branca, de olhos azuis", refletindo a confiança no momento brasileiro.',
                'metricas_globais'    => [
                    ['indicador' => 'Queda do PIB global em 2009', 'valor' => -2.1, 'unidade' => '%'],
                    ['indicador' => 'Valor em ativos destruídos globalmente', 'valor' => 11000, 'unidade' => 'bilhões USD'],
                ],
                'metricas_brasil'     => [
                    ['indicador' => 'Variação do PIB brasileiro em 2009', 'valor' => -0.1, 'unidade' => '%'],
                ],
                'categorias'          => ['econômica', 'financeira'],
                'content_slug'        => null,
            ],
            [
                'titulo'              => 'Primavera Árabe',
                'slug'                => 'primavera-arabe',
                'ano'                 => 2010,
                'data_inicio'         => '2010-12-17',
                'data_fim'            => '2012-12-31',
                'contexto_geopolitico' => 'A Primavera Árabe foi uma onda de protestos, revoltas e revoluções que varreram o mundo árabe a partir de dezembro de 2010, detonada pela autoimolação do vendedor ambulante tunisiano Mohamed Bouazizi. O movimento derrubou governos autoritários na Tunísia, Egito, Líbia e Iêmen, e gerou conflitos sangrentos na Síria, Barein e outros países. As causas estruturais incluíam desemprego elevado entre jovens, corrupção generalizada, desigualdade econômica, repressão política e a influência das redes sociais como instrumento de mobilização. O entusiasmo inicial com possibilidades democráticas logo deu lugar à contrarrevolução, golpes militares, guerras civis e ascensão de grupos islamistas. A Tunísia foi o único caso de transição democrática relativamente bem-sucedida, embora frágil. No restante, a Primavera Árabe deixou um rastro de instabilidade duradoura.',
                'impacto_global'      => 'A Primavera Árabe redesenhou o mapa político do Oriente Médio e Norte da África, gerando guerras civis, crises de refugiados e instabilidade que impactaram a segurança europeia. O vácuo de poder criado na Líbia e no Iêmen favoreceu o crescimento de grupos jihadistas. A crise síria, originada nesse contexto, gerou a maior crise de refugiados desde a Segunda Guerra Mundial, com mais de 5 milhões de deslocados internacionais.',
                'impacto_brasil'      => 'O Brasil acompanhou os eventos com cautela, equilibrando seu apoio às demandas democráticas com o princípio de não intervenção. O país absteve-se na votação da ONU sobre a intervenção na Líbia, evitando endossar operações militares. A instabilidade na região afetou os preços do petróleo e gerou incertezas para empresas brasileiras com presença no Norte da África.',
                'metricas_globais'    => [
                    ['indicador' => 'Países afetados por protestos significativos', 'valor' => 17, 'unidade' => 'países'],
                    ['indicador' => 'Refugiados sírios gerados indiretamente', 'valor' => 5600000, 'unidade' => 'pessoas'],
                ],
                'metricas_brasil'     => [
                    ['indicador' => 'Brasileiros repatriados da Líbia em 2011', 'valor' => 213, 'unidade' => 'pessoas'],
                ],
                'categorias'          => ['geopolítica', 'humanitária'],
                'content_slug'        => null,
            ],
            [
                'titulo'              => 'Crise da Dívida Europeia',
                'slug'                => 'crise-da-divida-europeia',
                'ano'                 => 2010,
                'data_inicio'         => '2010-04-23',
                'data_fim'            => '2018-08-20',
                'contexto_geopolitico' => 'A Crise da Dívida Europeia emergiu como consequência da crise financeira global de 2008, expondo as fragilidades estruturais da zona do euro: países com economias heterogêneas compartilhando uma moeda única sem mecanismos adequados de transferência fiscal. A Grécia foi o epicentro, revelando déficits e dívida pública muito superiores aos reportados, desencadeando uma crise de confiança que se propagou para Irlanda, Portugal, Espanha, Itália e Chipre. O BCE, FMI e Comissão Europeia (a "Troika") impuseram programas de austeridade severos como condição para resgates financeiros. A Grécia realizou a maior reestruturação de dívida soberana da história. A crise colocou em xeque a sobrevivência do euro e gerou intensa tensão política entre países do norte e sul europeu, além de ascensão de partidos extremistas.',
                'impacto_global'      => 'A crise europeia prolongou a recessão global pós-2008 e gerou anos de deflação e desemprego elevado na periferia europeia, com taxa de desemprego chegando a 27% na Grécia e Espanha. Forçou reformas estruturais profundas no sistema de governança da zona do euro, incluindo o mecanismo de estabilidade europeu e a união bancária. O sofrimento econômico alimentou movimentos eurocéticos e extremistas políticos, preparando o terreno para o Brexit.',
                'impacto_brasil'      => 'A crise europeia impactou negativamente o Brasil ao reduzir a demanda global, pressionar as exportações e aumentar a aversão ao risco nos mercados emergentes. O real se desvalorizou, as exportações de manufaturados para a Europa caíram e o crescimento brasileiro desacelerou. O país ampliou sua presença comercial na Ásia como diversificação estratégica diante da fragilidade europeia.',
                'metricas_globais'    => [
                    ['indicador' => 'Dívida pública grega no pico da crise (% do PIB)', 'valor' => 177, 'unidade' => '% do PIB'],
                    ['indicador' => 'Desemprego máximo na Grécia', 'valor' => 27.9, 'unidade' => '%'],
                ],
                'metricas_brasil'     => [
                    ['indicador' => 'Queda nas exportações brasileiras para UE (2011-2012)', 'valor' => -8.3, 'unidade' => '%'],
                ],
                'categorias'          => ['econômica', 'financeira'],
                'content_slug'        => null,
            ],
            [
                'titulo'              => 'Conflito na Síria',
                'slug'                => 'conflito-na-siria',
                'ano'                 => 2011,
                'data_inicio'         => '2011-03-15',
                'data_fim'            => null,
                'contexto_geopolitico' => 'O Conflito na Síria começou em março de 2011 como parte da Primavera Árabe, com protestos populares contra o regime de Bashar al-Assad. A resposta violenta do governo transformou o levante em uma guerra civil multidimensional envolvendo dezenas de grupos armados, potências regionais e internacionais. O conflito tornou-se um campo de batalha proxy entre Rússia e Irã (apoiando Assad) e EUA, Turquia e países do Golfo Pérsico (apoiando diferentes facções rebeldes). O surgimento do Estado Islâmico a partir de 2013 adicionou uma nova dimensão ao conflito. O uso de armas químicas pelo regime sírio violou normas internacionais sem consequências efetivas. O conflito gerou mais de 13 milhões de deslocados, tornou-se a maior crise humanitária do século XXI e destruiu sistematicamente o patrimônio histórico e cultural sírio.',
                'impacto_global'      => 'O conflito sírio gerou a maior crise de refugiados desde a Segunda Guerra Mundial, com mais de 5,6 milhões de refugiados internacionais e 6 milhões de deslocados internos. A crise migratória que atingiu a Europa em 2015 alterou profundamente a política do continente, alimentando movimentos extremistas e tensionando a coesão europeia. O conflito consolidou o retorno russo como potência militar global e testou os limites da ordem internacional baseada em regras.',
                'impacto_brasil'      => 'O Brasil recebeu contingente de refugiados sírios, com mais de 3.000 registrados pelo ACNUR no país. O Itamaraty buscou papel mediador nos foros multilaterais, defendendo solução política negociada. O conflito intensificou debates internos sobre política migratória, levando à aprovação da Lei de Migração de 2017, que ampliou direitos de refugiados no Brasil.',
                'metricas_globais'    => [
                    ['indicador' => 'Mortos no conflito (estimativa)', 'valor' => 500000, 'unidade' => 'pessoas'],
                    ['indicador' => 'Refugiados sírios internacionais', 'valor' => 5600000, 'unidade' => 'pessoas'],
                ],
                'metricas_brasil'     => [
                    ['indicador' => 'Refugiados sírios no Brasil', 'valor' => 3305, 'unidade' => 'pessoas'],
                ],
                'categorias'          => ['guerra', 'humanitária'],
                'content_slug'        => null,
            ],
            [
                'titulo'              => 'Crise da Crimeia',
                'slug'                => 'crise-da-crimeia',
                'ano'                 => 2014,
                'data_inicio'         => '2014-02-20',
                'data_fim'            => '2014-09-05',
                'contexto_geopolitico' => 'A Crise da Crimeia eclodiu após a queda do presidente pró-Rússia Viktor Yanukovych na Ucrânia, derrubado pelos protestos do Euromaidan. Aproveitando o vácuo político em Kiev, a Rússia enviou tropas sem identificação ("homenzinhos verdes") para a península da Crimeia em fevereiro de 2014. Um referendo contestado pela comunidade internacional aprovou a anexação da Crimeia à Rússia em março de 2014. Simultaneamente, rebeliões pró-Rússia eclodiram no leste ucraniano, nas regiões do Donbas, levando a um conflito armado de baixa intensidade que se estendeu por anos. A Rússia justificou as ações como proteção a russos étnicos e resposta à expansão da OTAN. O Ocidente respondeu com sanções econômicas que se tornaram as mais severas impostas à Rússia desde o fim da Guerra Fria.',
                'impacto_global'      => 'A anexação da Crimeia representou a primeira alteração forçada de fronteiras europeias desde a Segunda Guerra Mundial, violando o direito internacional e o Memorando de Budapeste de 1994. Marcou o retorno da geopolítica territorial à Europa e inaugurou uma nova fase de confronto entre Rússia e Ocidente. As sanções econômicas mútuas fragmentaram o comércio global e iniciaram um processo de desacoplamento geoeconômico entre a Rússia e o Ocidente.',
                'impacto_brasil'      => 'O Brasil adotou posição equidistante, abstendo-se na votação da ONU sobre a soberania ucraniana. O governo Dilma reafirmou o princípio da não intervenção e condenou o uso da força. As sanções ocidentais à Rússia abriram oportunidades para exportações brasileiras ao mercado russo, especialmente no agronegócio, substituindo produtos europeus vetados pela Rússia.',
                'metricas_globais'    => [
                    ['indicador' => 'Área da Crimeia anexada', 'valor' => 27000, 'unidade' => 'km²'],
                    ['indicador' => 'Queda do rublo em 2014', 'valor' => -40, 'unidade' => '%'],
                ],
                'metricas_brasil'     => [
                    ['indicador' => 'Crescimento das exportações agrícolas ao mercado russo (2014-2015)', 'valor' => 22, 'unidade' => '%'],
                ],
                'categorias'          => ['guerra', 'geopolítica'],
                'content_slug'        => null,
            ],
            [
                'titulo'              => 'Surgimento do Estado Islâmico',
                'slug'                => 'surgimento-do-estado-islamico',
                'ano'                 => 2014,
                'data_inicio'         => '2014-06-10',
                'data_fim'            => '2019-03-23',
                'contexto_geopolitico' => 'O Estado Islâmico (EI, ISIS, ISIL ou Daesh) proclamou seu califado em junho de 2014, após capturar Mosul, a segunda maior cidade do Iraque, com um exército de apenas 1.500 combatentes derrotando 30.000 soldados iraquianos. O grupo surgiu das cinzas da Al-Qaeda no Iraque, aproveitando o vácuo de poder criado pela retirada americana e a exclusão política dos sunitas pelo governo xiita de Nouri al-Maliki. Em seu auge, o EI controlou território equivalente ao Reino Unido, com cerca de 8 a 12 milhões de pessoas sob seu domínio, infraestrutura estatal, receitas de petróleo e uma sofisticada máquina de propaganda digital. O califado atraiu milhares de combatentes estrangeiros de mais de 80 países e inspirou ataques terroristas em todo o mundo. Uma coalizão internacional de 60 países combateu o grupo ao longo de cinco anos até a derrota territorial em Baghouz em março de 2019.',
                'impacto_global'      => 'O Estado Islâmico redefiniu o terrorismo global na era digital, usando redes sociais para recrutar, propagar e inspirar ataques em todo o mundo. Ataques em Paris, Bruxelas, Niza, Berlim, Londres e dezenas de outras cidades ocidentais geraram ondas de xenofobia, islamofobia e restrições às liberdades civis. A derrota territorial não eliminou a ameaça: o grupo se adaptou à insurgência e continua ativo na África e na Ásia.',
                'impacto_brasil'      => 'O Brasil reforçou medidas de segurança especialmente durante a Copa do Mundo de 2014 e os Jogos Olímpicos de 2016, aproveitando o momento de alta ameaça global. A Abin e a Polícia Federal ampliaram sua capacidade de monitoramento de redes jihadistas. O país deportou alguns suspeitos de ligação com grupos extremistas e intensificou cooperação com agências de inteligência internacionais.',
                'metricas_globais'    => [
                    ['indicador' => 'Território máximo controlado', 'valor' => 209000, 'unidade' => 'km²'],
                    ['indicador' => 'Combatentes estrangeiros recrutados', 'valor' => 40000, 'unidade' => 'pessoas'],
                ],
                'metricas_brasil'     => [
                    ['indicador' => 'Brasileiros com suspeita de ligação ao EI investigados', 'valor' => 17, 'unidade' => 'casos'],
                ],
                'categorias'          => ['terrorismo', 'guerra'],
                'content_slug'        => null,
            ],
            [
                'titulo'              => 'Brexit',
                'slug'                => 'brexit',
                'ano'                 => 2016,
                'data_inicio'         => '2016-06-23',
                'data_fim'            => '2020-12-31',
                'contexto_geopolitico' => 'O Brexit foi o processo pelo qual o Reino Unido votou, em referendo de junho de 2016, pela saída da União Europeia, numa das maiores surpresas políticas da história recente. O resultado de 51,9% pelo Leave foi impulsionado por uma combinação de eurocetismo histórico britânico, narrativas sobre soberania, imigração e financiamento à UE, além do descontentamento de regiões economicamente marginalizadas. O processo gerou anos de paralisia política em Westminster, três primeiros-ministros, duas eleições gerais e negociações exaustivas. O Acordo de Saída foi finalmente aprovado em janeiro de 2020, com a saída efetiva do mercado único e da união aduaneira no final de 2020. O Brexit redefiniu as relações entre Londres e Bruxelas, gerou fricções comerciais significativas e abriu questões sobre o futuro da Irlanda do Norte e a unidade territorial do próprio Reino Unido.',
                'impacto_global'      => 'O Brexit enfraqueceu a União Europeia ao perder sua segunda maior economia e um de seus dois países com assento permanente no Conselho de Segurança da ONU. Impulsionou movimentos eurocéticos em toda a Europa. A incerteza prolongada impactou investimentos no Reino Unido, desvalorizou a libra esterlina e alterou cadeias produtivas. O evento sinalizou a fragilidade do projeto de integração europeia e o crescimento do nacionalismo econômico.',
                'impacto_brasil'      => 'O Brexit gerou incertezas para o acordo comercial entre Mercosul e União Europeia, obrigando o bloco a considerar negociações separadas com o Reino Unido. A desvalorização da libra impactou negativamente as exportações brasileiras para o mercado britânico. A comunidade brasileira no Reino Unido — estimada em 300 mil pessoas — enfrentou insegurança quanto ao status migratório pós-Brexit.',
                'metricas_globais'    => [
                    ['indicador' => 'Percentual de votos pelo Leave', 'valor' => 51.9, 'unidade' => '%'],
                    ['indicador' => 'Desvalorização da libra após referendo', 'valor' => -12, 'unidade' => '%'],
                ],
                'metricas_brasil'     => [
                    ['indicador' => 'Brasileiros residentes no Reino Unido', 'valor' => 300000, 'unidade' => 'pessoas'],
                ],
                'categorias'          => ['geopolítica', 'econômica'],
                'content_slug'        => null,
            ],
            [
                'titulo'              => 'Guerra Comercial EUA-China',
                'slug'                => 'guerra-comercial-eua-china',
                'ano'                 => 2018,
                'data_inicio'         => '2018-03-22',
                'data_fim'            => '2020-01-15',
                'contexto_geopolitico' => 'A Guerra Comercial EUA-China foi iniciada pelo governo Trump em março de 2018 com a imposição de tarifas sobre aço e alumínio, seguidas por tarifas sobre US$ 250 bilhões em produtos chineses. Os EUA acusavam a China de práticas comerciais desleais, roubo de propriedade intelectual, subsídios estatais e manipulação cambial. A China retalhou com tarifas sobre produtos americanos, especialmente agrícolas. A disputa escalou ao longo de 2018 e 2019, afetando cadeias produtivas globais, aumentando custos para consumidores e empresas e gerando instabilidade nos mercados financeiros. A chamada "Fase 1" do acordo, assinada em janeiro de 2020, suspendeu temporariamente a escalada, mas não resolveu as questões estruturais. A rivalidade comercial faz parte de uma competição geoeconômica mais ampla pelo domínio tecnológico, incluindo a disputa pela liderança em 5G e semicondutores.',
                'impacto_global'      => 'A guerra comercial fragmentou o sistema multilateral de comércio e sinalizou o fim da globalização irrestrita. Forçou empresas globais a revisar cadeias de suprimento, gerando reshoring e nearshoring. A disputa por liderança em tecnologias estratégicas (5G, IA, semicondutores) deu início a uma rivalidade geoeconômica estrutural que remoldará a ordem econômica global. O multilateralismo comercial sob a OMC foi severamente enfraquecido.',
                'impacto_brasil'      => 'O Brasil foi um dos maiores beneficiários da guerra comercial: com tarifas sobre a soja americana, a China ampliou dramaticamente suas compras de soja brasileira. As exportações de soja ao mercado chinês saltaram e os preços das commodities agrícolas se elevaram. Porém, a incerteza global também afetou negativamente os fluxos de investimento e as condições financeiras dos mercados emergentes.',
                'metricas_globais'    => [
                    ['indicador' => 'Volume de comércio bilateral afetado por tarifas', 'valor' => 360, 'unidade' => 'bilhões USD'],
                    ['indicador' => 'Queda do comércio global em 2019', 'valor' => -0.1, 'unidade' => '%'],
                ],
                'metricas_brasil'     => [
                    ['indicador' => 'Crescimento das exportações de soja ao mercado chinês (2018)', 'valor' => 24.5, 'unidade' => '%'],
                ],
                'categorias'          => ['econômica', 'geopolítica'],
                'content_slug'        => null,
            ],
            [
                'titulo'              => 'Pandemia COVID-19',
                'slug'                => 'pandemia-covid-19',
                'ano'                 => 2020,
                'data_inicio'         => '2020-01-30',
                'data_fim'            => '2023-05-05',
                'contexto_geopolitico' => 'A Pandemia de COVID-19 foi declarada pela OMS em 30 de janeiro de 2020 como emergência de saúde pública internacional e em 11 de março de 2020 como pandemia. O vírus SARS-CoV-2, identificado pela primeira vez em Wuhan, China, em dezembro de 2019, se espalhou para praticamente todos os países do mundo em questão de meses. A pandemia levou a lockdowns sem precedentes, colapso de sistemas de saúde, paralisação de cadeias produtivas globais e a maior contração econômica desde a Grande Depressão. O desenvolvimento acelerado de vacinas — com aprovação emergencial em menos de um ano, tempo recorde — foi considerado um triunfo científico. Porém, a distribuição desigual de vacinas entre países ricos e pobres gerou críticas sobre o "apartheid vacinal". A pandemia acelerou tendências existentes como digitalização, trabalho remoto e desglobalização.',
                'impacto_global'      => 'A pandemia matou mais de 7 milhões de pessoas oficialmente (com estimativas de excesso de mortalidade bem superiores), contraiu o PIB global em 3,3% em 2020 e gerou a maior expansão de dívida pública desde a Segunda Guerra Mundial. Acelerou a digitalização da economia, fragilizou cadeias de suprimento globais e expôs desigualdades estruturais. O conflito geopolítico entre EUA e China sobre a origem do vírus aprofundou a rivalidade estratégica entre as duas potências.',
                'impacto_brasil'      => 'O Brasil foi um dos países mais afetados pela pandemia, com mais de 700 mil mortes oficiais — a segunda maior morte absoluta do mundo. A gestão federal controversa, com negacionismo e atrasos na vacinação, gerou críticas internacionais e profundou polarização política. Economicamente, o auxílio emergencial de R$600/mês beneficiou 68 milhões de pessoas, mas gerou pressão fiscal expressiva sobre as contas públicas.',
                'metricas_globais'    => [
                    ['indicador' => 'Mortes globais oficiais', 'valor' => 7000000, 'unidade' => 'pessoas'],
                    ['indicador' => 'Contração do PIB global em 2020', 'valor' => -3.3, 'unidade' => '%'],
                ],
                'metricas_brasil'     => [
                    ['indicador' => 'Mortes no Brasil', 'valor' => 700000, 'unidade' => 'pessoas'],
                ],
                'categorias'          => ['humanitária', 'econômica'],
                'content_slug'        => null,
            ],
            [
                'titulo'              => 'Conflito Etiópia-Tigré',
                'slug'                => 'conflito-etiopia-tigre',
                'ano'                 => 2020,
                'data_inicio'         => '2020-11-04',
                'data_fim'            => '2022-11-02',
                'contexto_geopolitico' => 'O Conflito de Tigré foi uma guerra civil na Etiópia iniciada em novembro de 2020, quando o governo federal do primeiro-ministro Abiy Ahmed, vencedor do Prêmio Nobel da Paz de 2019, ordenou operação militar contra o governante regional da Frente de Libertação do Povo do Tigré (TPLF), que havia dominado a política etíope por décadas. O conflito rapidamente se tornou uma das crises humanitárias mais severas do mundo, com denúncias de massacre, uso de fome como arma de guerra, violência sexual sistemática e ataque a civis. Eritreia entrou no conflito ao lado do governo federal. O bloqueio da região de Tigré impediu a chegada de ajuda humanitária, com relatórios da ONU sobre condições de fome próximas à catástrofe afetando milhões. O cessar-fogo permanente foi alcançado em novembro de 2022 com a mediação da União Africana.',
                'impacto_global'      => 'O conflito expôs as limitações dos mecanismos africanos e internacionais de prevenção e resolução de conflitos, além de testar a credibilidade do Prêmio Nobel da Paz. Gerou debates sobre o papel da União Africana na resolução de conflitos no continente e sobre a responsabilidade da comunidade internacional de intervir. As violações de direitos humanos documentadas alimentaram discussões sobre accountability e o Tribunal Penal Internacional.',
                'impacto_brasil'      => 'O Brasil acompanhou o conflito com preocupação, tendo investimentos em infraestrutura na Etiópia via construtoras brasileiras. O Itamaraty apoiou os esforços de mediação e emitiu alertas de viagem para a região. A crise humanitária gerou demandas por contribuições ao Programa Mundial de Alimentos, do qual o Brasil é um dos maiores contribuintes históricos.',
                'metricas_globais'    => [
                    ['indicador' => 'Pessoas em necessidade de assistência humanitária', 'valor' => 9000000, 'unidade' => 'pessoas'],
                    ['indicador' => 'Deslocados internos estimados', 'valor' => 2000000, 'unidade' => 'pessoas'],
                ],
                'metricas_brasil'     => [
                    ['indicador' => 'Contribuição brasileira ao Programa Mundial de Alimentos (2021)', 'valor' => 15, 'unidade' => 'milhões USD'],
                ],
                'categorias'          => ['guerra', 'humanitária'],
                'content_slug'        => null,
            ],
            [
                'titulo'              => 'Invasão Russa da Ucrânia',
                'slug'                => 'invasao-russa-da-ucrania',
                'ano'                 => 2022,
                'data_inicio'         => '2022-02-24',
                'data_fim'            => null,
                'contexto_geopolitico' => 'A Invasão Russa da Ucrânia em larga escala foi iniciada em 24 de fevereiro de 2022, quando Putin ordenou uma "operação militar especial" contra a Ucrânia, com ataques simultâneos em múltiplas frentes incluindo Kiev, o sul e o leste do país. A Rússia alegou como justificativas a "desnazificação" da Ucrânia, proteção de russos étnicos no Donbas e oposição à expansão da OTAN. A comunidade internacional respondeu com as sanções mais severas já impostas a uma grande potência, enquanto dezenas de países forneceram armas e assistência militar à Ucrânia. A guerra expôs vulnerabilidades energéticas europeias, redefiniu a arquitetura de segurança do continente e acelerou a expansão da OTAN, com Finlândia e Suécia abandonando a neutralidade histórica. O conflito se transformou na maior guerra convencional da Europa desde 1945 e permanece em curso.',
                'impacto_global'      => 'A guerra na Ucrânia desencadeou a maior crise de segurança europeia desde a Segunda Guerra Mundial, generalizou o debate sobre deterrência nuclear e remodelou a geopolítica global. As sanções ocidentais aceleraram a fragmentação da economia global em blocos geoeconômicos. O bloqueio de exportações de grãos causou crise alimentar global, afetando especialmente países em desenvolvimento. A guerra acelerou a transição energética europeia e a corrida por segurança de suprimentos críticos.',
                'impacto_brasil'      => 'O Brasil adotou posição neutra, abstendo-se em votos da ONU sobre condenação à Rússia, gerando tensões com parceiros ocidentais. Economicamente, o conflito beneficiou exportadores brasileiros de alimentos e energia, elevando preços de soja, milho, petróleo e fertilizantes. Porém, a alta nos preços de fertilizantes — dos quais o Brasil é altamente dependente, com 85% importados — impactou negativamente os custos da agricultura.',
                'metricas_globais'    => [
                    ['indicador' => 'Refugiados ucranianos no exterior', 'valor' => 6500000, 'unidade' => 'pessoas'],
                    ['indicador' => 'Custo estimado de reconstrução da Ucrânia', 'valor' => 411000, 'unidade' => 'bilhões USD'],
                ],
                'metricas_brasil'     => [
                    ['indicador' => 'Alta nos preços de fertilizantes para o agronegócio brasileiro (2022)', 'valor' => 80, 'unidade' => '%'],
                ],
                'categorias'          => ['guerra', 'geopolítica'],
                'content_slug'        => null,
            ],
            [
                'titulo'              => 'Crise Energética Europeia',
                'slug'                => 'crise-energetica-europeia',
                'ano'                 => 2022,
                'data_inicio'         => '2022-02-24',
                'data_fim'            => '2023-12-31',
                'contexto_geopolitico' => 'A Crise Energética Europeia foi precipitada pela invasão russa da Ucrânia em fevereiro de 2022 e pelas sanções ocidentais subsequentes, que interromperam progressivamente o fornecimento de gás natural russo para a Europa. A Rússia havia sido responsável por cerca de 40% do fornecimento de gás da União Europeia, e a interrupção dessa dependência em meses gerou desafios sem precedentes. A explosão dos gasodutos Nord Stream em setembro de 2022 agravou ainda mais a situação. Os preços do gás natural na Europa atingiram níveis recordes, gerando inflação energética, ameaças à competitividade industrial e necessidade urgente de diversificação. A Europa respondeu com racionalização do consumo, aceleração de renováveis, reativação de usinas a carvão e acordos de emergência para GNL com EUA, Qatar e outros fornecedores. O inverno de 2022-2023 foi atravessado sem o temido colapso, mas com custos elevados.',
                'impacto_global'      => 'A crise energética europeia acelerou a transição para energias renováveis e redefiniu as rotas do comércio global de energia. O GNL americano ganhou enorme importância estratégica. Os preços elevados de energia alimentaram inflação global e forçaram bancos centrais a elevar taxas de juros, gerando pressões sobre economias emergentes. A crise consolidou a "geopolitização da energia" como tema central da nova ordem mundial.',
                'impacto_brasil'      => 'A crise energética europeia abriu oportunidades significativas para o Brasil como exportador de GNL e petróleo. A Petrobras ampliou exportações para a Europa, e o país foi reconhecido como potencial fornecedor estratégico de longo prazo. A alta nos preços globais de energia beneficiou os exportadores brasileiros, mas também elevou custos internos de combustíveis, pressionando a inflação doméstica.',
                'metricas_globais'    => [
                    ['indicador' => 'Alta no preço do gás TTF na Europa (pico 2022)', 'valor' => 335, 'unidade' => '% em relação à média histórica'],
                    ['indicador' => 'Redução no consumo de gás da UE (2022-2023)', 'valor' => -15, 'unidade' => '%'],
                ],
                'metricas_brasil'     => [
                    ['indicador' => 'Crescimento das exportações de petróleo ao mercado europeu (2022)', 'valor' => 31, 'unidade' => '%'],
                ],
                'categorias'          => ['econômica', 'energética'],
                'content_slug'        => null,
            ],
            [
                'titulo'              => 'Conflito Israel-Hamas',
                'slug'                => 'conflito-israel-hamas',
                'ano'                 => 2023,
                'data_inicio'         => '2023-10-07',
                'data_fim'            => null,
                'contexto_geopolitico' => 'O Conflito Israel-Hamas escalou dramaticamente com o ataque surpresa do Hamas em 7 de outubro de 2023 contra Israel, o mais sangrento da história do país: cerca de 1.200 israelenses foram mortos e 251 tomados como reféns em Gaza. Israel respondeu com uma campanha militar de grande escala em Gaza, declarando estado de guerra e impondo bloqueio total ao território. A operação militar israelense resultou em dezenas de milhares de mortos palestinos, destruição massiva de infraestrutura civil e uma crise humanitária catastrófica, com denúncias de crimes de guerra por ambos os lados nos tribunais internacionais. O conflito gerou protestos em todo o mundo, polarizou opiniões sobre o Oriente Médio e ameaçou se expandir regionalmente com o envolvimento do Hezbollah, dos Houthis e do Irã. O processo de normalização dos Acordos de Abraham foi suspenso e a solução de dois Estados foi recolocada no centro do debate.',
                'impacto_global'      => 'O conflito dividiu profundamente a comunidade internacional sobre a questão palestina, testou os limites do direito internacional humanitário e gerou intenso debate sobre genocídio. O envolvimento dos Houthis nos ataques a navios no Mar Vermelho afetou o comércio global. A escalada regional envolvendo Irã e Israel em troca de ataques diretos em abril de 2024 representou um perigoso novo patamar de confrontação. A crise acelerou questionamentos sobre a ordem baseada em regras e duplos padrões internacionais.',
                'impacto_brasil'      => 'O Brasil defendeu o cessar-fogo nos foros multilaterais e foi representado pelo presidente Lula, que fez declarações polêmicas comparando ações israelenses ao Holocausto, gerando tensões diplomáticas e expulsão do embaixador israelense. O país tem comunidades significativas de descendentes árabes e judeus, gerando pressões domésticas nas duas direções. O conflito impactou investimentos e relações comerciais com Israel.',
                'metricas_globais'    => [
                    ['indicador' => 'Mortos em Gaza (estimativa ONU)', 'valor' => 45000, 'unidade' => 'pessoas'],
                    ['indicador' => 'Deslocados em Gaza', 'valor' => 1900000, 'unidade' => 'pessoas'],
                ],
                'metricas_brasil'     => [
                    ['indicador' => 'Brasileiros mortos ou desaparecidos no ataque de 7/10', 'valor' => 9, 'unidade' => 'pessoas'],
                ],
                'categorias'          => ['guerra', 'humanitária'],
                'content_slug'        => null,
            ],
            [
                'titulo'              => 'Instabilidade no Sahel',
                'slug'                => 'instabilidade-no-sahel',
                'ano'                 => 2023,
                'data_inicio'         => '2023-07-26',
                'data_fim'            => null,
                'contexto_geopolitico' => 'A Instabilidade no Sahel atingiu um novo patamar a partir de 2023, com a série de golpes militares que varreram a região desde 2021 — Mali (2021), Burkina Faso (2022), Níger (2023) e Gabão (2023). O golpe no Níger em julho de 2023 foi particularmente significativo: o país era considerado o último parceiro confiável do Ocidente no Sahel e lar de uma importante base militar americana e presença francesa. As juntas militares expulsaram forças francesas e americanas, buscando novos parceiros de segurança como a Rússia (Grupo Wagner). A região enfrenta uma convergência de crises: insurgências jihadistas ligadas à Al-Qaeda e ao Estado Islâmico, mudanças climáticas destruindo meios de subsistência, pobreza extrema e colapso da governança. A CEDEAO ameaçou intervenção militar no Níger, mas recuou. A saída da influência francesa e ocidental da região reconfigurou os equilíbrios de poder na África Ocidental.',
                'impacto_global'      => 'A onda de golpes no Sahel representa a maior retração da influência ocidental na África desde as independências e abre espaço para influência russa e chinesa na região. A instabilidade aumenta o fluxo migratório para a Europa via Mediterrâneo, alimentando crises políticas no continente. O colapso da contenção jihadista no Sahel representa uma ameaça de segurança crescente com potencial de expansão para o norte da África e Europa.',
                'impacto_brasil'      => 'O Brasil acompanha a crise com atenção crescente, dada sua política de diversificação de parcerias na África. A saída da influência francesa pode criar oportunidades para o aprofundamento de relações bilaterais com os novos governos. O Itamaraty monitora a situação visando proteger brasileiros na região e mantendo presença diplomática para preservar influência em fórum multilateral africano.',
                'metricas_globais'    => [
                    ['indicador' => 'Golpes de Estado na região Sahel desde 2020', 'valor' => 8, 'unidade' => 'golpes'],
                    ['indicador' => 'Pessoas deslocadas por conflitos jihadistas no Sahel', 'valor' => 3500000, 'unidade' => 'pessoas'],
                ],
                'metricas_brasil'     => [
                    ['indicador' => 'Embaixadas brasileiras em países do Sahel afetados', 'valor' => 3, 'unidade' => 'postos diplomáticos'],
                ],
                'categorias'          => ['guerra', 'geopolítica'],
                'content_slug'        => null,
            ],
            [
                'titulo'              => 'Tensões no Mar do Sul da China',
                'slug'                => 'tensoes-no-mar-do-sul-da-china',
                'ano'                 => 2023,
                'data_inicio'         => '2023-01-01',
                'data_fim'            => null,
                'contexto_geopolitico' => 'As Tensões no Mar do Sul da China escalaram significativamente em 2023, com a China intensificando suas atividades militares e paramilitares em áreas reivindicadas pelas Filipinas, Vietnã, Malásia, Brunei e Taiwan. A China reivindica aproximadamente 90% do Mar do Sul da China com base na chamada "linha dos dez traços", rejeitada por um tribunal internacional em 2016. As colisões de navios de guarda-costeiras e ataques a embarcações filipinas com canhões d\'água se tornaram frequentes no Segundo Banco Thomas. Os EUA intensificaram operações de liberdade de navegação (FONOPs) e fortaleceram alianças com Filipinas, Austrália e Japão através de arranjos como o AUKUS e o Quad. Taiwan permanece como o ponto de maior tensão, com exercícios militares chineses em escala crescente. A competição pela liderança regional entre China e EUA torna o Mar do Sul da China um dos pontos de maior risco de conflito acidental da geopolítica contemporânea.',
                'impacto_global'      => 'As tensões no Mar do Sul da China ameaçam uma das rotas marítimas mais importantes do mundo, por onde passam cerca de US$ 3,4 trilhões em comércio anualmente. Uma escalada militar poderia interromper cadeias de suprimento globais, especialmente no setor de semicondutores centrado em Taiwan. A rivalidade sino-americana na região está acelerando a corrida armamentista no Pacífico e induzindo países da região a escolher lados na nova bipolaridade.',
                'impacto_brasil'      => 'O Brasil observa as tensões com atenção crescente, pois qualquer conflito envolvendo Taiwan impactaria gravemente as exportações brasileiras à China, o maior parceiro comercial do país. Uma crise de semicondutores decorrente de conflito em Taiwan afetaria profundamente a indústria brasileira. O país defende solução pacífica e dialogo, mantendo relações comerciais tanto com China quanto com os EUA e suas alianças no Indo-Pacífico.',
                'metricas_globais'    => [
                    ['indicador' => 'Comércio global que passa pelo Mar do Sul da China', 'valor' => 3400, 'unidade' => 'bilhões USD/ano'],
                    ['indicador' => 'Incremento no orçamento militar da China (2023)', 'valor' => 7.2, 'unidade' => '%'],
                ],
                'metricas_brasil'     => [
                    ['indicador' => 'Parcela das exportações brasileiras destinadas à China', 'valor' => 26.8, 'unidade' => '%'],
                ],
                'categorias'          => ['geopolítica', 'naval'],
                'content_slug'        => null,
            ],
            [
                'titulo'              => 'Crise do Canal do Suez / Ataques Houthis',
                'slug'                => 'crise-do-canal-do-suez-ataques-houthis',
                'ano'                 => 2024,
                'data_inicio'         => '2023-11-19',
                'data_fim'            => null,
                'contexto_geopolitico' => 'A crise da navegação no Mar Vermelho emergiu em novembro de 2023 quando os Houthis do Iêmen, em solidariedade à causa palestina durante o conflito em Gaza, iniciaram ataques a navios comerciais com drones, mísseis balísticos e antinavis no estreito de Bab el-Mandeb e no Mar Vermelho. Os ataques forçaram as principais companhias de navegação a desviar suas rotas pelo Cabo da Boa Esperança, ao redor da África, evitando o Canal de Suez. Os EUA e Reino Unido responderam com operação militar contra infraestrutura dos Houthis no Iêmen (Operação Prosperity Guardian), mas os ataques continuaram. A perturbação nas rotas marítimas afetou 15% do comércio global que normalmente passa pelo Canal de Suez, elevando fretes, atrasando entregas e impactando cadeias de suprimento mundiais, especialmente no setor automotivo europeu e asiático.',
                'impacto_global'      => 'Os ataques Houthis demonstraram como um ator não-estatal relativamente modesto pode criar perturbações massivas no comércio global. Os custos de frete aumentaram entre 150% e 300%, afetando preços de bens manufaturados globalmente. O desvio pelo Cabo da Boa Esperança adicionou 10 a 14 dias às viagens entre Ásia e Europa, elevando emissões de CO2. A crise evidenciou a fragilidade das cadeias de suprimento globais hiperespecializadas e a vulnerabilidade da globalização a choques geopolíticos regionais.',
                'impacto_brasil'      => 'O Brasil foi impactado por dois ângulos: o aumento nos fretes encareceu as importações de insumos industriais, mas o desvio de rotas pelo Cabo da Boa Esperança beneficiou portos brasileiros como pontos de escala e reabastecimento. A crise reafirmou a importância estratégica da posição geográfica brasileira no Atlântico Sul e abriu discussões sobre o papel dos portos nacionais nas novas rotas globais.',
                'metricas_globais'    => [
                    ['indicador' => 'Queda no tráfego pelo Canal de Suez', 'valor' => -40, 'unidade' => '%'],
                    ['indicador' => 'Aumento médio nos fretes marítimos globais', 'valor' => 220, 'unidade' => '%'],
                ],
                'metricas_brasil'     => [
                    ['indicador' => 'Aumento no tempo de trânsito de importações da Ásia para o Brasil', 'valor' => 12, 'unidade' => 'dias adicionais'],
                ],
                'categorias'          => ['logística', 'guerra'],
                'content_slug'        => null,
            ],
        ];

        foreach ($crises as $dados) {
            CriseHistorica::updateOrCreate(
                ['slug' => $dados['slug']],
                $dados
            );
        }
    }
}
