<?php

namespace Database\Seeders;

use App\Models\PerfilPais;
use Illuminate\Database\Seeder;

class PaisesInicialSeeder extends Seeder
{
    public function run(): void
    {
        $paises = [
            // América do Norte
            ['codigo_pais' => 'US', 'nome_pt' => 'Estados Unidos', 'bandeira_emoji' => '🇺🇸', 'regiao_geopolitica' => 'América do Norte', 'indicadores_relevantes' => ['PIB', 'Fed Rate', 'Dívida/PIB', 'CPI'], 'termos_busca' => ['United States', 'EUA', 'Washington', 'Fed', 'Trump'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'CA', 'nome_pt' => 'Canadá', 'bandeira_emoji' => '🇨🇦', 'regiao_geopolitica' => 'América do Norte', 'indicadores_relevantes' => ['PIB', 'CAD', 'Petróleo', 'BoC Rate'], 'termos_busca' => ['Canada', 'Canadá', 'Ottawa', 'Trudeau', 'Bank of Canada'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'MX', 'nome_pt' => 'México', 'bandeira_emoji' => '🇲🇽', 'regiao_geopolitica' => 'América do Norte', 'indicadores_relevantes' => ['PIB', 'Peso', 'Remessas', 'Nearshoring'], 'termos_busca' => ['Mexico', 'México', 'CDMX', 'Sheinbaum', 'Banxico'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],

            // América Central
            ['codigo_pais' => 'GT', 'nome_pt' => 'Guatemala', 'bandeira_emoji' => '🇬🇹', 'regiao_geopolitica' => 'América Central', 'indicadores_relevantes' => ['PIB', 'Quetzal', 'Remessas', 'Café'], 'termos_busca' => ['Guatemala', 'Guatemala City', 'Arévalo'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'BZ', 'nome_pt' => 'Belize', 'bandeira_emoji' => '🇧🇿', 'regiao_geopolitica' => 'América Central', 'indicadores_relevantes' => ['PIB', 'Dólar Belizenho', 'Turismo'], 'termos_busca' => ['Belize', 'Belmopan', 'Briceño'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'HN', 'nome_pt' => 'Honduras', 'bandeira_emoji' => '🇭🇳', 'regiao_geopolitica' => 'América Central', 'indicadores_relevantes' => ['PIB', 'Lempira', 'Remessas', 'Café'], 'termos_busca' => ['Honduras', 'Tegucigalpa', 'Castro'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'SV', 'nome_pt' => 'El Salvador', 'bandeira_emoji' => '🇸🇻', 'regiao_geopolitica' => 'América Central', 'indicadores_relevantes' => ['PIB', 'Dólar', 'Bitcoin', 'Remessas'], 'termos_busca' => ['El Salvador', 'San Salvador', 'Bukele', 'Bitcoin'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'NI', 'nome_pt' => 'Nicarágua', 'bandeira_emoji' => '🇳🇮', 'regiao_geopolitica' => 'América Central', 'indicadores_relevantes' => ['PIB', 'Córdoba', 'Sanções', 'Café'], 'termos_busca' => ['Nicaragua', 'Nicarágua', 'Managua', 'Ortega'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'CR', 'nome_pt' => 'Costa Rica', 'bandeira_emoji' => '🇨🇷', 'regiao_geopolitica' => 'América Central', 'indicadores_relevantes' => ['PIB', 'Colón', 'Turismo', 'Tecnologia'], 'termos_busca' => ['Costa Rica', 'San José', 'Chaves'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'PA', 'nome_pt' => 'Panamá', 'bandeira_emoji' => '🇵🇦', 'regiao_geopolitica' => 'América Central', 'indicadores_relevantes' => ['PIB', 'Dólar', 'Canal', 'Finanças'], 'termos_busca' => ['Panama', 'Panamá', 'Cidade do Panamá', 'Canal do Panamá'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],

            // Caribe
            ['codigo_pais' => 'CU', 'nome_pt' => 'Cuba', 'bandeira_emoji' => '🇨🇺', 'regiao_geopolitica' => 'Caribe', 'indicadores_relevantes' => ['PIB', 'Peso', 'Sanções', 'Turismo'], 'termos_busca' => ['Cuba', 'Havana', 'Díaz-Canel', 'Castro'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'JM', 'nome_pt' => 'Jamaica', 'bandeira_emoji' => '🇯🇲', 'regiao_geopolitica' => 'Caribe', 'indicadores_relevantes' => ['PIB', 'Dólar Jamaicano', 'Turismo'], 'termos_busca' => ['Jamaica', 'Kingston', 'Holness'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'HT', 'nome_pt' => 'Haiti', 'bandeira_emoji' => '🇭🇹', 'regiao_geopolitica' => 'Caribe', 'indicadores_relevantes' => ['PIB', 'Gourde', 'Instabilidade'], 'termos_busca' => ['Haiti', 'Port-au-Prince', 'gangues', 'crise'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'DO', 'nome_pt' => 'República Dominicana', 'bandeira_emoji' => '🇩🇴', 'regiao_geopolitica' => 'Caribe', 'indicadores_relevantes' => ['PIB', 'Peso', 'Turismo', 'Remessas'], 'termos_busca' => ['República Dominicana', 'Santo Domingo', 'Abinader'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'TT', 'nome_pt' => 'Trinidad e Tobago', 'bandeira_emoji' => '🇹🇹', 'regiao_geopolitica' => 'Caribe', 'indicadores_relevantes' => ['PIB', 'Dólar TTD', 'Gás Natural', 'Petróleo'], 'termos_busca' => ['Trinidad', 'Tobago', 'Port of Spain', 'Rowley'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'BB', 'nome_pt' => 'Barbados', 'bandeira_emoji' => '🇧🇧', 'regiao_geopolitica' => 'Caribe', 'indicadores_relevantes' => ['PIB', 'Dólar BDS', 'Turismo'], 'termos_busca' => ['Barbados', 'Bridgetown', 'Mottley'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'BS', 'nome_pt' => 'Bahamas', 'bandeira_emoji' => '🇧🇸', 'regiao_geopolitica' => 'Caribe', 'indicadores_relevantes' => ['PIB', 'Dólar BSD', 'Turismo', 'Finanças'], 'termos_busca' => ['Bahamas', 'Nassau', 'Davis'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],

            // América do Sul
            ['codigo_pais' => 'BR', 'nome_pt' => 'Brasil', 'bandeira_emoji' => '🇧🇷', 'regiao_geopolitica' => 'América do Sul', 'indicadores_relevantes' => ['PIB', 'Selic', 'IPCA', 'Câmbio'], 'termos_busca' => ['Brasil', 'Brasília', 'Lula', 'Banco Central', 'IPCA'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'AR', 'nome_pt' => 'Argentina', 'bandeira_emoji' => '🇦🇷', 'regiao_geopolitica' => 'América do Sul', 'indicadores_relevantes' => ['PIB', 'Peso', 'Inflação', 'FMI', 'Reservas'], 'termos_busca' => ['Argentina', 'Buenos Aires', 'Milei', 'BCRA', 'dólar'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'CL', 'nome_pt' => 'Chile', 'bandeira_emoji' => '🇨🇱', 'regiao_geopolitica' => 'América do Sul', 'indicadores_relevantes' => ['PIB', 'Peso', 'Cobre', 'Lítio'], 'termos_busca' => ['Chile', 'Santiago', 'Boric', 'cobre', 'lítio'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'CO', 'nome_pt' => 'Colômbia', 'bandeira_emoji' => '🇨🇴', 'regiao_geopolitica' => 'América do Sul', 'indicadores_relevantes' => ['PIB', 'Peso', 'Petróleo', 'Café'], 'termos_busca' => ['Colombia', 'Colômbia', 'Bogotá', 'Petro', 'FARC'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'PE', 'nome_pt' => 'Peru', 'bandeira_emoji' => '🇵🇪', 'regiao_geopolitica' => 'América do Sul', 'indicadores_relevantes' => ['PIB', 'Sol', 'Mineração', 'Cobre'], 'termos_busca' => ['Peru', 'Lima', 'Boluarte', 'mineração'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'VE', 'nome_pt' => 'Venezuela', 'bandeira_emoji' => '🇻🇪', 'regiao_geopolitica' => 'América do Sul', 'indicadores_relevantes' => ['Petróleo', 'Inflação', 'Bolívar', 'Sanções'], 'termos_busca' => ['Venezuela', 'Caracas', 'Maduro', 'PDVSA', 'petróleo'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'EC', 'nome_pt' => 'Equador', 'bandeira_emoji' => '🇪🇨', 'regiao_geopolitica' => 'América do Sul', 'indicadores_relevantes' => ['PIB', 'Dólar', 'Petróleo', 'Bananas'], 'termos_busca' => ['Ecuador', 'Equador', 'Quito', 'Noboa', 'petróleo'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'BO', 'nome_pt' => 'Bolívia', 'bandeira_emoji' => '🇧🇴', 'regiao_geopolitica' => 'América do Sul', 'indicadores_relevantes' => ['PIB', 'Boliviano', 'Lítio', 'Gás'], 'termos_busca' => ['Bolivia', 'Bolívia', 'Sucre', 'La Paz', 'Arce', 'lítio'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'PY', 'nome_pt' => 'Paraguai', 'bandeira_emoji' => '🇵🇾', 'regiao_geopolitica' => 'América do Sul', 'indicadores_relevantes' => ['PIB', 'Guarani', 'Soja', 'Energia'], 'termos_busca' => ['Paraguay', 'Paraguai', 'Assunção', 'Santiago Peña'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'UY', 'nome_pt' => 'Uruguai', 'bandeira_emoji' => '🇺🇾', 'regiao_geopolitica' => 'América do Sul', 'indicadores_relevantes' => ['PIB', 'Peso', 'Soja', 'Turismo'], 'termos_busca' => ['Uruguay', 'Uruguai', 'Montevidéu', 'Orsi'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'GY', 'nome_pt' => 'Guiana', 'bandeira_emoji' => '🇬🇾', 'regiao_geopolitica' => 'América do Sul', 'indicadores_relevantes' => ['PIB', 'Dólar GYD', 'Petróleo', 'Crescimento'], 'termos_busca' => ['Guyana', 'Guiana', 'Georgetown', 'Ali', 'petróleo offshore'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'SR', 'nome_pt' => 'Suriname', 'bandeira_emoji' => '🇸🇷', 'regiao_geopolitica' => 'América do Sul', 'indicadores_relevantes' => ['PIB', 'Dólar SRD', 'Petróleo', 'Bauxita'], 'termos_busca' => ['Suriname', 'Paramaribo', 'Santokhi'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],

            // Europa Ocidental
            ['codigo_pais' => 'GB', 'nome_pt' => 'Reino Unido', 'bandeira_emoji' => '🇬🇧', 'regiao_geopolitica' => 'Europa Ocidental', 'indicadores_relevantes' => ['PIB', 'Libra', 'CPI', 'BoE Rate'], 'termos_busca' => ['United Kingdom', 'Reino Unido', 'Londres', 'BoE', 'Starmer'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'FR', 'nome_pt' => 'França', 'bandeira_emoji' => '🇫🇷', 'regiao_geopolitica' => 'Europa Ocidental', 'indicadores_relevantes' => ['PIB', 'CPI', 'Exportações', 'CAC 40'], 'termos_busca' => ['France', 'França', 'Paris', 'Macron', 'Élysée'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'DE', 'nome_pt' => 'Alemanha', 'bandeira_emoji' => '🇩🇪', 'regiao_geopolitica' => 'Europa Ocidental', 'indicadores_relevantes' => ['PIB', 'IPC', 'Exportações', 'PMI'], 'termos_busca' => ['Alemanha', 'Berlim', 'Bundesbank', 'DAX', 'Merz'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'IT', 'nome_pt' => 'Itália', 'bandeira_emoji' => '🇮🇹', 'regiao_geopolitica' => 'Europa Ocidental', 'indicadores_relevantes' => ['PIB', 'Dívida/PIB', 'FTSE MIB', 'Exportações'], 'termos_busca' => ['Italy', 'Itália', 'Roma', 'Meloni', 'BCE'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'ES', 'nome_pt' => 'Espanha', 'bandeira_emoji' => '🇪🇸', 'regiao_geopolitica' => 'Europa Ocidental', 'indicadores_relevantes' => ['PIB', 'Desemprego', 'IBEX 35', 'Turismo'], 'termos_busca' => ['Spain', 'Espanha', 'Madri', 'Sánchez', 'IBEX'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'PT', 'nome_pt' => 'Portugal', 'bandeira_emoji' => '🇵🇹', 'regiao_geopolitica' => 'Europa Ocidental', 'indicadores_relevantes' => ['PIB', 'Turismo', 'Dívida', 'Exportações'], 'termos_busca' => ['Portugal', 'Lisboa', 'Montenegro', 'PSI-20'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'NL', 'nome_pt' => 'Países Baixos', 'bandeira_emoji' => '🇳🇱', 'regiao_geopolitica' => 'Europa Ocidental', 'indicadores_relevantes' => ['PIB', 'AEX', 'Exportações', 'Logística'], 'termos_busca' => ['Netherlands', 'Países Baixos', 'Amsterdã', 'Schoof', 'Wilders'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'BE', 'nome_pt' => 'Bélgica', 'bandeira_emoji' => '🇧🇪', 'regiao_geopolitica' => 'Europa Ocidental', 'indicadores_relevantes' => ['PIB', 'BEL 20', 'Exportações', 'Dívida'], 'termos_busca' => ['Belgium', 'Bélgica', 'Bruxelas', 'De Wever', 'NATO'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'CH', 'nome_pt' => 'Suíça', 'bandeira_emoji' => '🇨🇭', 'regiao_geopolitica' => 'Europa Ocidental', 'indicadores_relevantes' => ['PIB', 'Franco Suíço', 'Juros SNB', 'Finanças'], 'termos_busca' => ['Switzerland', 'Suíça', 'Berna', 'SNB', 'Davos'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'AT', 'nome_pt' => 'Áustria', 'bandeira_emoji' => '🇦🇹', 'regiao_geopolitica' => 'Europa Ocidental', 'indicadores_relevantes' => ['PIB', 'ATX', 'Exportações', 'Turismo'], 'termos_busca' => ['Austria', 'Áustria', 'Viena', 'Kickl'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'SE', 'nome_pt' => 'Suécia', 'bandeira_emoji' => '🇸🇪', 'regiao_geopolitica' => 'Europa Ocidental', 'indicadores_relevantes' => ['PIB', 'Coroa', 'OMXS30', 'NATO'], 'termos_busca' => ['Sweden', 'Suécia', 'Estocolmo', 'Kristersson', 'OMXS'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'NO', 'nome_pt' => 'Noruega', 'bandeira_emoji' => '🇳🇴', 'regiao_geopolitica' => 'Europa Ocidental', 'indicadores_relevantes' => ['PIB', 'Coroa', 'Petróleo', 'Fundo Soberano'], 'termos_busca' => ['Norway', 'Noruega', 'Oslo', 'Støre', 'Equinor'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'DK', 'nome_pt' => 'Dinamarca', 'bandeira_emoji' => '🇩🇰', 'regiao_geopolitica' => 'Europa Ocidental', 'indicadores_relevantes' => ['PIB', 'Coroa', 'Exportações', 'Energia Eólica'], 'termos_busca' => ['Denmark', 'Dinamarca', 'Copenhague', 'Frederiksen', 'Groenlândia'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'FI', 'nome_pt' => 'Finlândia', 'bandeira_emoji' => '🇫🇮', 'regiao_geopolitica' => 'Europa Ocidental', 'indicadores_relevantes' => ['PIB', 'Euro', 'Exportações', 'NATO'], 'termos_busca' => ['Finland', 'Finlândia', 'Helsinque', 'Orpo'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'IE', 'nome_pt' => 'Irlanda', 'bandeira_emoji' => '🇮🇪', 'regiao_geopolitica' => 'Europa Ocidental', 'indicadores_relevantes' => ['PIB', 'FDI', 'Tecnologia', 'ISEQ'], 'termos_busca' => ['Ireland', 'Irlanda', 'Dublin', 'Martin', 'Apple', 'Google'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'LU', 'nome_pt' => 'Luxemburgo', 'bandeira_emoji' => '🇱🇺', 'regiao_geopolitica' => 'Europa Ocidental', 'indicadores_relevantes' => ['PIB per capita', 'Finanças', 'FDI'], 'termos_busca' => ['Luxembourg', 'Luxemburgo', 'Bettel', 'fintech'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'IS', 'nome_pt' => 'Islândia', 'bandeira_emoji' => '🇮🇸', 'regiao_geopolitica' => 'Europa Ocidental', 'indicadores_relevantes' => ['PIB', 'Coroa Islandesa', 'Turismo', 'Pesca'], 'termos_busca' => ['Iceland', 'Islândia', 'Reykjavik', 'Jakobsdóttir'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],

            // Europa Oriental
            ['codigo_pais' => 'PL', 'nome_pt' => 'Polônia', 'bandeira_emoji' => '🇵🇱', 'regiao_geopolitica' => 'Europa Oriental', 'indicadores_relevantes' => ['PIB', 'Zloty', 'Inflação', 'Defesa'], 'termos_busca' => ['Poland', 'Polônia', 'Varsóvia', 'Tusk', 'NATO'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'CZ', 'nome_pt' => 'República Tcheca', 'bandeira_emoji' => '🇨🇿', 'regiao_geopolitica' => 'Europa Oriental', 'indicadores_relevantes' => ['PIB', 'Coroa Tcheca', 'Exportações', 'Automóveis'], 'termos_busca' => ['Czech Republic', 'Tchéquia', 'Praga', 'Fiala'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'SK', 'nome_pt' => 'Eslováquia', 'bandeira_emoji' => '🇸🇰', 'regiao_geopolitica' => 'Europa Oriental', 'indicadores_relevantes' => ['PIB', 'Euro', 'Automóveis', 'FDI'], 'termos_busca' => ['Slovakia', 'Eslováquia', 'Bratislava', 'Fico'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'HU', 'nome_pt' => 'Hungria', 'bandeira_emoji' => '🇭🇺', 'regiao_geopolitica' => 'Europa Oriental', 'indicadores_relevantes' => ['PIB', 'Forint', 'Inflação', 'FDI'], 'termos_busca' => ['Hungary', 'Hungria', 'Budapeste', 'Orbán', 'Rússia'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'RO', 'nome_pt' => 'Romênia', 'bandeira_emoji' => '🇷🇴', 'regiao_geopolitica' => 'Europa Oriental', 'indicadores_relevantes' => ['PIB', 'Leu', 'Déficit', 'Energia'], 'termos_busca' => ['Romania', 'Romênia', 'Bucareste', 'Ciolacu'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'BG', 'nome_pt' => 'Bulgária', 'bandeira_emoji' => '🇧🇬', 'regiao_geopolitica' => 'Europa Oriental', 'indicadores_relevantes' => ['PIB', 'Lev', 'Exportações', 'Energia'], 'termos_busca' => ['Bulgaria', 'Bulgária', 'Sofia', 'Denkov'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'HR', 'nome_pt' => 'Croácia', 'bandeira_emoji' => '🇭🇷', 'regiao_geopolitica' => 'Europa Oriental', 'indicadores_relevantes' => ['PIB', 'Euro', 'Turismo', 'FDI'], 'termos_busca' => ['Croatia', 'Croácia', 'Zagreb', 'Plenković'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'SI', 'nome_pt' => 'Eslovênia', 'bandeira_emoji' => '🇸🇮', 'regiao_geopolitica' => 'Europa Oriental', 'indicadores_relevantes' => ['PIB', 'Euro', 'Exportações', 'Turismo'], 'termos_busca' => ['Slovenia', 'Eslovênia', 'Liubliana', 'Golob'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'BA', 'nome_pt' => 'Bósnia e Herzegovina', 'bandeira_emoji' => '🇧🇦', 'regiao_geopolitica' => 'Europa Oriental', 'indicadores_relevantes' => ['PIB', 'Marco Conversível', 'UE', 'Instabilidade'], 'termos_busca' => ['Bosnia', 'Bósnia', 'Sarajevo', 'Dodik'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'RS', 'nome_pt' => 'Sérvia', 'bandeira_emoji' => '🇷🇸', 'regiao_geopolitica' => 'Europa Oriental', 'indicadores_relevantes' => ['PIB', 'Dinar', 'FDI', 'Kosovo'], 'termos_busca' => ['Serbia', 'Sérvia', 'Belgrado', 'Vučić', 'Kosovo'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'ME', 'nome_pt' => 'Montenegro', 'bandeira_emoji' => '🇲🇪', 'regiao_geopolitica' => 'Europa Oriental', 'indicadores_relevantes' => ['PIB', 'Euro', 'Turismo', 'NATO'], 'termos_busca' => ['Montenegro', 'Podgorica', 'Spajić'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'MK', 'nome_pt' => 'Macedônia do Norte', 'bandeira_emoji' => '🇲🇰', 'regiao_geopolitica' => 'Europa Oriental', 'indicadores_relevantes' => ['PIB', 'Denar', 'NATO', 'UE'], 'termos_busca' => ['North Macedonia', 'Macedônia', 'Skopje', 'Mickoski'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'AL', 'nome_pt' => 'Albânia', 'bandeira_emoji' => '🇦🇱', 'regiao_geopolitica' => 'Europa Oriental', 'indicadores_relevantes' => ['PIB', 'Lek', 'Remessas', 'NATO'], 'termos_busca' => ['Albania', 'Albânia', 'Tirana', 'Rama'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'EE', 'nome_pt' => 'Estônia', 'bandeira_emoji' => '🇪🇪', 'regiao_geopolitica' => 'Europa Oriental', 'indicadores_relevantes' => ['PIB', 'Euro', 'Digital', 'Defesa'], 'termos_busca' => ['Estonia', 'Estônia', 'Tallinn', 'Kallas', 'e-Estonia'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'LV', 'nome_pt' => 'Letônia', 'bandeira_emoji' => '🇱🇻', 'regiao_geopolitica' => 'Europa Oriental', 'indicadores_relevantes' => ['PIB', 'Euro', 'NATO', 'Defesa'], 'termos_busca' => ['Latvia', 'Letônia', 'Riga', 'Silina'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'LT', 'nome_pt' => 'Lituânia', 'bandeira_emoji' => '🇱🇹', 'regiao_geopolitica' => 'Europa Oriental', 'indicadores_relevantes' => ['PIB', 'Euro', 'NATO', 'Defesa'], 'termos_busca' => ['Lithuania', 'Lituânia', 'Vilnius', 'Paluckas'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],

            // Espaço Pós-Soviético / Europa Oriental
            ['codigo_pais' => 'RU', 'nome_pt' => 'Rússia', 'bandeira_emoji' => '🇷🇺', 'regiao_geopolitica' => 'Europa Oriental', 'indicadores_relevantes' => ['PIB', 'Rublo', 'Petróleo', 'Reservas'], 'termos_busca' => ['Russia', 'Moscou', 'Putin', 'Kremlin', 'MOEX'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'UA', 'nome_pt' => 'Ucrânia', 'bandeira_emoji' => '🇺🇦', 'regiao_geopolitica' => 'Europa Oriental', 'indicadores_relevantes' => ['PIB', 'Hryvnia', 'Dívida', 'Reconstrução'], 'termos_busca' => ['Ukraine', 'Ucrânia', 'Kiev', 'Zelensky', 'guerra'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'BY', 'nome_pt' => 'Bielorrússia', 'bandeira_emoji' => '🇧🇾', 'regiao_geopolitica' => 'Europa Oriental', 'indicadores_relevantes' => ['PIB', 'Rublo Bielorrusso', 'Sanções', 'Rússia'], 'termos_busca' => ['Belarus', 'Bielorrússia', 'Minsk', 'Lukashenko'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'MD', 'nome_pt' => 'Moldávia', 'bandeira_emoji' => '🇲🇩', 'regiao_geopolitica' => 'Europa Oriental', 'indicadores_relevantes' => ['PIB', 'Leu Moldavo', 'Remessas', 'Energia'], 'termos_busca' => ['Moldova', 'Moldávia', 'Chisinau', 'Sandu', 'Transnístria'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],

            // Cáucaso
            ['codigo_pais' => 'GE', 'nome_pt' => 'Geórgia', 'bandeira_emoji' => '🇬🇪', 'regiao_geopolitica' => 'Cáucaso', 'indicadores_relevantes' => ['PIB', 'Lari', 'Turismo', 'UE'], 'termos_busca' => ['Georgia', 'Geórgia', 'Tbilisi', 'Kobakhidze', 'Sonho Georgiano'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'AM', 'nome_pt' => 'Armênia', 'bandeira_emoji' => '🇦🇲', 'regiao_geopolitica' => 'Cáucaso', 'indicadores_relevantes' => ['PIB', 'Dram', 'Remessas', 'Azerbaijão'], 'termos_busca' => ['Armenia', 'Armênia', 'Yerevan', 'Pashinyan', 'Nagorno-Karabakh'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'AZ', 'nome_pt' => 'Azerbaijão', 'bandeira_emoji' => '🇦🇿', 'regiao_geopolitica' => 'Cáucaso', 'indicadores_relevantes' => ['PIB', 'Manat', 'Petróleo', 'Gás'], 'termos_busca' => ['Azerbaijan', 'Azerbaijão', 'Baku', 'Aliyev', 'SOCAR'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],

            // Ásia Central
            ['codigo_pais' => 'KZ', 'nome_pt' => 'Cazaquistão', 'bandeira_emoji' => '🇰🇿', 'regiao_geopolitica' => 'Ásia Central', 'indicadores_relevantes' => ['PIB', 'Tenge', 'Petróleo', 'Urânio'], 'termos_busca' => ['Kazakhstan', 'Cazaquistão', 'Astana', 'Tokayev', 'Tengiz'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'UZ', 'nome_pt' => 'Uzbequistão', 'bandeira_emoji' => '🇺🇿', 'regiao_geopolitica' => 'Ásia Central', 'indicadores_relevantes' => ['PIB', 'Som', 'Gás', 'Ouro'], 'termos_busca' => ['Uzbekistan', 'Uzbequistão', 'Tashkent', 'Mirziyoyev'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'TM', 'nome_pt' => 'Turcomenistão', 'bandeira_emoji' => '🇹🇲', 'regiao_geopolitica' => 'Ásia Central', 'indicadores_relevantes' => ['PIB', 'Manat TMT', 'Gás Natural', 'Isolamento'], 'termos_busca' => ['Turkmenistan', 'Turcomenistão', 'Ashgabat', 'Berdymukhammedov'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'TJ', 'nome_pt' => 'Tadjiquistão', 'bandeira_emoji' => '🇹🇯', 'regiao_geopolitica' => 'Ásia Central', 'indicadores_relevantes' => ['PIB', 'Somoni', 'Remessas', 'Alumínio'], 'termos_busca' => ['Tajikistan', 'Tadjiquistão', 'Dushanbe', 'Rahmon'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'KG', 'nome_pt' => 'Quirguistão', 'bandeira_emoji' => '🇰🇬', 'regiao_geopolitica' => 'Ásia Central', 'indicadores_relevantes' => ['PIB', 'Som KGS', 'Ouro', 'Remessas'], 'termos_busca' => ['Kyrgyzstan', 'Quirguistão', 'Bishkek', 'Japarov'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],

            // Oriente Médio
            ['codigo_pais' => 'SA', 'nome_pt' => 'Arábia Saudita', 'bandeira_emoji' => '🇸🇦', 'regiao_geopolitica' => 'Oriente Médio', 'indicadores_relevantes' => ['Petróleo', 'PIB', 'Reservas', 'OPEC'], 'termos_busca' => ['Saudi Arabia', 'Arábia Saudita', 'Riad', 'MBS', 'Aramco'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'IR', 'nome_pt' => 'Irã', 'bandeira_emoji' => '🇮🇷', 'regiao_geopolitica' => 'Oriente Médio', 'indicadores_relevantes' => ['Petróleo', 'Inflação', 'Rial', 'Sanções'], 'termos_busca' => ['Iran', 'Irã', 'Teerã', 'Khamenei', 'IRGC'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'IL', 'nome_pt' => 'Israel', 'bandeira_emoji' => '🇮🇱', 'regiao_geopolitica' => 'Oriente Médio', 'indicadores_relevantes' => ['PIB', 'Shekel', 'Déficit', 'CPI'], 'termos_busca' => ['Israel', 'Tel Aviv', 'Netanyahu', 'IDF', 'Gaza'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'TR', 'nome_pt' => 'Turquia', 'bandeira_emoji' => '🇹🇷', 'regiao_geopolitica' => 'Oriente Médio', 'indicadores_relevantes' => ['Lira', 'Inflação', 'PIB', 'Juro TCMB'], 'termos_busca' => ['Turkey', 'Turquia', 'Ancara', 'Erdogan', 'TCMB'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'IQ', 'nome_pt' => 'Iraque', 'bandeira_emoji' => '🇮🇶', 'regiao_geopolitica' => 'Oriente Médio', 'indicadores_relevantes' => ['Petróleo', 'PIB', 'Dinar', 'Reconstrução'], 'termos_busca' => ['Iraq', 'Iraque', 'Bagdá', 'Al-Sudani', 'OPEC'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'SY', 'nome_pt' => 'Síria', 'bandeira_emoji' => '🇸🇾', 'regiao_geopolitica' => 'Oriente Médio', 'indicadores_relevantes' => ['PIB', 'Libra Síria', 'Reconstrução', 'Refugiados'], 'termos_busca' => ['Syria', 'Síria', 'Damasco', 'Al-Sharaa', 'HTS', 'Assad', 'guerra civil'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'JO', 'nome_pt' => 'Jordânia', 'bandeira_emoji' => '🇯🇴', 'regiao_geopolitica' => 'Oriente Médio', 'indicadores_relevantes' => ['PIB', 'Dinar', 'Remessas', 'Ajuda'], 'termos_busca' => ['Jordan', 'Jordânia', 'Amã', 'Rei Abdullah', 'refugiados'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'LB', 'nome_pt' => 'Líbano', 'bandeira_emoji' => '🇱🇧', 'regiao_geopolitica' => 'Oriente Médio', 'indicadores_relevantes' => ['PIB', 'Libra Libanesa', 'Crise', 'Hezbollah'], 'termos_busca' => ['Lebanon', 'Líbano', 'Beirute', 'Salam', 'Hezbollah', 'crise econômica'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'YE', 'nome_pt' => 'Iêmen', 'bandeira_emoji' => '🇾🇪', 'regiao_geopolitica' => 'Oriente Médio', 'indicadores_relevantes' => ['PIB', 'Rial Iemenita', 'Guerra', 'Houthis'], 'termos_busca' => ['Yemen', 'Iêmen', 'Sanaa', 'Houthis', 'guerra', 'Mar Vermelho'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'KW', 'nome_pt' => 'Kuwait', 'bandeira_emoji' => '🇰🇼', 'regiao_geopolitica' => 'Oriente Médio', 'indicadores_relevantes' => ['Petróleo', 'PIB', 'Dinar', 'OPEC'], 'termos_busca' => ['Kuwait', 'Kuwait City', 'Al-Sabah', 'KNPC', 'petróleo'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'QA', 'nome_pt' => 'Catar', 'bandeira_emoji' => '🇶🇦', 'regiao_geopolitica' => 'Oriente Médio', 'indicadores_relevantes' => ['Gás Natural', 'PIB per capita', 'Riyal', 'LNG'], 'termos_busca' => ['Qatar', 'Catar', 'Doha', 'Al Thani', 'LNG', 'QIA'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'AE', 'nome_pt' => 'Emirados Árabes Unidos', 'bandeira_emoji' => '🇦🇪', 'regiao_geopolitica' => 'Oriente Médio', 'indicadores_relevantes' => ['PIB', 'Dirham', 'Petróleo', 'Finanças'], 'termos_busca' => ['UAE', 'Emirados', 'Dubai', 'Abu Dhabi', 'MBZ', 'ADNOC'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'BH', 'nome_pt' => 'Barein', 'bandeira_emoji' => '🇧🇭', 'regiao_geopolitica' => 'Oriente Médio', 'indicadores_relevantes' => ['PIB', 'Dinar', 'Petróleo', 'Finanças'], 'termos_busca' => ['Bahrain', 'Barein', 'Manama', 'Al Khalifa'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'OM', 'nome_pt' => 'Omã', 'bandeira_emoji' => '🇴🇲', 'regiao_geopolitica' => 'Oriente Médio', 'indicadores_relevantes' => ['Petróleo', 'Rial Omanense', 'PIB', 'Gás'], 'termos_busca' => ['Oman', 'Omã', 'Mascate', 'Sultan Haitham', 'OIA'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'PS', 'nome_pt' => 'Palestina', 'bandeira_emoji' => '🇵🇸', 'regiao_geopolitica' => 'Oriente Médio', 'indicadores_relevantes' => ['PIB', 'Ajuda Internacional', 'Bloqueio', 'Conflito'], 'termos_busca' => ['Palestine', 'Palestina', 'Gaza', 'Cisjordânia', 'Hamas', 'Abbas'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'CY', 'nome_pt' => 'Chipre', 'bandeira_emoji' => '🇨🇾', 'regiao_geopolitica' => 'Oriente Médio', 'indicadores_relevantes' => ['PIB', 'Euro', 'Turismo', 'Finanças'], 'termos_busca' => ['Cyprus', 'Chipre', 'Nicósia', 'Christodoulides', 'Turquia'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],

            // África do Norte
            ['codigo_pais' => 'EG', 'nome_pt' => 'Egito', 'bandeira_emoji' => '🇪🇬', 'regiao_geopolitica' => 'África do Norte', 'indicadores_relevantes' => ['PIB', 'Libra Egípcia', 'Canal de Suez', 'Turismo'], 'termos_busca' => ['Egypt', 'Egito', 'Cairo', 'Al-Sisi', 'Suez', 'FMI'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'LY', 'nome_pt' => 'Líbia', 'bandeira_emoji' => '🇱🇾', 'regiao_geopolitica' => 'África do Norte', 'indicadores_relevantes' => ['Petróleo', 'PIB', 'Dinar', 'Instabilidade'], 'termos_busca' => ['Libya', 'Líbia', 'Trípoli', 'NOC', 'guerra civil'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'TN', 'nome_pt' => 'Tunísia', 'bandeira_emoji' => '🇹🇳', 'regiao_geopolitica' => 'África do Norte', 'indicadores_relevantes' => ['PIB', 'Dinar', 'Turismo', 'FMI'], 'termos_busca' => ['Tunisia', 'Tunísia', 'Túnis', 'Saied'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'DZ', 'nome_pt' => 'Argélia', 'bandeira_emoji' => '🇩🇿', 'regiao_geopolitica' => 'África do Norte', 'indicadores_relevantes' => ['Petróleo', 'Gás', 'Dinar', 'PIB'], 'termos_busca' => ['Algeria', 'Argélia', 'Argel', 'Tebboune', 'Sonatrach'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'MA', 'nome_pt' => 'Marrocos', 'bandeira_emoji' => '🇲🇦', 'regiao_geopolitica' => 'África do Norte', 'indicadores_relevantes' => ['PIB', 'Dirham', 'Fosfato', 'Turismo'], 'termos_busca' => ['Morocco', 'Marrocos', 'Rabat', 'Rei Mohammed VI', 'OCP', 'Saara'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'SD', 'nome_pt' => 'Sudão', 'bandeira_emoji' => '🇸🇩', 'regiao_geopolitica' => 'África do Norte', 'indicadores_relevantes' => ['PIB', 'Libra Sudanesa', 'Guerra', 'Crise'], 'termos_busca' => ['Sudan', 'Sudão', 'Cartum', 'RSF', 'SAF', 'guerra civil'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'MR', 'nome_pt' => 'Mauritânia', 'bandeira_emoji' => '🇲🇷', 'regiao_geopolitica' => 'África do Norte', 'indicadores_relevantes' => ['PIB', 'Ouguiya', 'Minério de Ferro', 'Pesca'], 'termos_busca' => ['Mauritania', 'Mauritânia', 'Nouakchott', 'Ghazouani'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],

            // África Ocidental
            ['codigo_pais' => 'NG', 'nome_pt' => 'Nigéria', 'bandeira_emoji' => '🇳🇬', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Naira', 'Petróleo', 'Inflação'], 'termos_busca' => ['Nigeria', 'Nigéria', 'Abuja', 'Tinubu', 'NNPC'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'GH', 'nome_pt' => 'Gana', 'bandeira_emoji' => '🇬🇭', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Cedi', 'Ouro', 'Cacau'], 'termos_busca' => ['Ghana', 'Gana', 'Acra', 'Mahama', 'ouro', 'cacau'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'CI', 'nome_pt' => 'Costa do Marfim', 'bandeira_emoji' => '🇨🇮', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Franco CFA', 'Cacau', 'Crescimento'], 'termos_busca' => ['Ivory Coast', 'Costa do Marfim', 'Abidjan', 'Ouattara', 'cacau'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'SN', 'nome_pt' => 'Senegal', 'bandeira_emoji' => '🇸🇳', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Franco CFA', 'Petróleo', 'Pesca'], 'termos_busca' => ['Senegal', 'Dakar', 'Faye', 'petróleo offshore'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'ML', 'nome_pt' => 'Mali', 'bandeira_emoji' => '🇲🇱', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Franco CFA', 'Ouro', 'Instabilidade'], 'termos_busca' => ['Mali', 'Bamako', 'junta', 'Wagner', 'Goïta', 'AES'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'BF', 'nome_pt' => 'Burkina Faso', 'bandeira_emoji' => '🇧🇫', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Franco CFA', 'Ouro', 'Jihadismo'], 'termos_busca' => ['Burkina Faso', 'Ouagadougou', 'Traoré', 'junta', 'AES'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'NE', 'nome_pt' => 'Níger', 'bandeira_emoji' => '🇳🇪', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Franco CFA', 'Urânio', 'Petróleo'], 'termos_busca' => ['Niger', 'Níger', 'Niamey', 'Tiani', 'junta', 'AES'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'GN', 'nome_pt' => 'Guiné', 'bandeira_emoji' => '🇬🇳', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Franco Guineense', 'Bauxita', 'Ouro'], 'termos_busca' => ['Guinea', 'Guiné', 'Conakry', 'Mamadi Doumbouya', 'junta'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'SL', 'nome_pt' => 'Serra Leoa', 'bandeira_emoji' => '🇸🇱', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Leone', 'Diamantes', 'Mineração'], 'termos_busca' => ['Sierra Leone', 'Serra Leoa', 'Freetown', 'Bio'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'LR', 'nome_pt' => 'Libéria', 'bandeira_emoji' => '🇱🇷', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Dólar LRD', 'Mineração', 'Borracha'], 'termos_busca' => ['Liberia', 'Libéria', 'Monróvia', 'Boakai'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'TG', 'nome_pt' => 'Togo', 'bandeira_emoji' => '🇹🇬', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Franco CFA', 'Fosfato', 'Porto'], 'termos_busca' => ['Togo', 'Lomé', 'Gnassingbé'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'BJ', 'nome_pt' => 'Benim', 'bandeira_emoji' => '🇧🇯', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Franco CFA', 'Algodão', 'Porto'], 'termos_busca' => ['Benin', 'Benim', 'Cotonou', 'Talon'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'CV', 'nome_pt' => 'Cabo Verde', 'bandeira_emoji' => '🇨🇻', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Escudo', 'Turismo', 'Remessas'], 'termos_busca' => ['Cape Verde', 'Cabo Verde', 'Praia', 'Neves'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'GW', 'nome_pt' => 'Guiné-Bissau', 'bandeira_emoji' => '🇬🇼', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Franco CFA', 'Castanha de Caju', 'Instabilidade'], 'termos_busca' => ['Guinea-Bissau', 'Guiné-Bissau', 'Bissau', 'Sissoco Embaló'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'GM', 'nome_pt' => 'Gâmbia', 'bandeira_emoji' => '🇬🇲', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Dalasi', 'Turismo', 'Remessas'], 'termos_busca' => ['Gambia', 'Gâmbia', 'Banjul', 'Barrow'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],

            // África Central
            ['codigo_pais' => 'CM', 'nome_pt' => 'Camarões', 'bandeira_emoji' => '🇨🇲', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Franco CFA', 'Petróleo', 'Cacau'], 'termos_busca' => ['Cameroon', 'Camarões', 'Yaoundé', 'Biya', 'Ambazônia'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'TD', 'nome_pt' => 'Chade', 'bandeira_emoji' => '🇹🇩', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Franco CFA', 'Petróleo', 'Instabilidade'], 'termos_busca' => ['Chad', 'Chade', 'Ndjamena', 'Mahamat Déby'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'CF', 'nome_pt' => 'República Centro-Africana', 'bandeira_emoji' => '🇨🇫', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Franco CFA', 'Diamantes', 'Wagner'], 'termos_busca' => ['Central African Republic', 'RCA', 'Bangui', 'Touadéra', 'Wagner'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'CG', 'nome_pt' => 'República do Congo', 'bandeira_emoji' => '🇨🇬', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Franco CFA', 'Petróleo', 'Madeira'], 'termos_busca' => ['Congo Republic', 'Congo-Brazzaville', 'Brazzaville', 'Sassou Nguesso'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'CD', 'nome_pt' => 'República Democrática do Congo', 'bandeira_emoji' => '🇨🇩', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Franco Congolês', 'Coltan', 'Conflito'], 'termos_busca' => ['DRC', 'Congo RDC', 'Kinshasa', 'Tshisekedi', 'M23', 'coltan'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'GA', 'nome_pt' => 'Gabão', 'bandeira_emoji' => '🇬🇦', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['Petróleo', 'PIB', 'Franco CFA', 'Madeira'], 'termos_busca' => ['Gabon', 'Gabão', 'Libreville', 'Oligui', 'junta'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'GQ', 'nome_pt' => 'Guiné Equatorial', 'bandeira_emoji' => '🇬🇶', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['Petróleo', 'PIB', 'Franco CFA'], 'termos_busca' => ['Equatorial Guinea', 'Guiné Equatorial', 'Malabo', 'Obiang'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],

            // África Oriental
            ['codigo_pais' => 'ET', 'nome_pt' => 'Etiópia', 'bandeira_emoji' => '🇪🇹', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Birr', 'Crescimento', 'Conflito'], 'termos_busca' => ['Ethiopia', 'Etiópia', 'Adis Abeba', 'Abiy Ahmed', 'Tigré'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'KE', 'nome_pt' => 'Quênia', 'bandeira_emoji' => '🇰🇪', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Xelim Queniano', 'Turismo', 'Tecnologia'], 'termos_busca' => ['Kenya', 'Quênia', 'Nairóbi', 'Ruto', 'M-Pesa'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'TZ', 'nome_pt' => 'Tanzânia', 'bandeira_emoji' => '🇹🇿', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Xelim Tanzaniano', 'Turismo', 'Ouro'], 'termos_busca' => ['Tanzania', 'Tanzânia', 'Dodoma', 'Hassan', 'Kilimanjaro'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'UG', 'nome_pt' => 'Uganda', 'bandeira_emoji' => '🇺🇬', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Xelim Ugandense', 'Petróleo', 'Café'], 'termos_busca' => ['Uganda', 'Kampala', 'Museveni', 'petróleo'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'RW', 'nome_pt' => 'Ruanda', 'bandeira_emoji' => '🇷🇼', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Franco Ruandês', 'Crescimento', 'Congo'], 'termos_busca' => ['Rwanda', 'Ruanda', 'Kigali', 'Kagame', 'M23'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'BI', 'nome_pt' => 'Burundi', 'bandeira_emoji' => '🇧🇮', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Franco Burundês', 'Café', 'Instabilidade'], 'termos_busca' => ['Burundi', 'Gitega', 'Ndayishimiye'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'SO', 'nome_pt' => 'Somália', 'bandeira_emoji' => '🇸🇴', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Xelim Somali', 'Al-Shabaab', 'Ajuda'], 'termos_busca' => ['Somalia', 'Somália', 'Mogadíscio', 'Hassan Sheikh', 'Al-Shabaab'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'DJ', 'nome_pt' => 'Djibuti', 'bandeira_emoji' => '🇩🇯', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Franco DJF', 'Porto', 'Bases Militares'], 'termos_busca' => ['Djibouti', 'Djibuti', 'Guelleh', 'bases militares', 'Mar Vermelho'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'ER', 'nome_pt' => 'Eritreia', 'bandeira_emoji' => '🇪🇷', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Nakfa', 'Mineração', 'Isolamento'], 'termos_busca' => ['Eritrea', 'Eritreia', 'Asmara', 'Afwerki'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'SS', 'nome_pt' => 'Sudão do Sul', 'bandeira_emoji' => '🇸🇸', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['Petróleo', 'PIB', 'Libra SSP', 'Conflito'], 'termos_busca' => ['South Sudan', 'Sudão do Sul', 'Juba', 'Kiir', 'Machar', 'guerra'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'MG', 'nome_pt' => 'Madagáscar', 'bandeira_emoji' => '🇲🇬', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Ariary', 'Mineração', 'Baunilha'], 'termos_busca' => ['Madagascar', 'Madagáscar', 'Antananarivo', 'Rajoelina'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'MZ', 'nome_pt' => 'Moçambique', 'bandeira_emoji' => '🇲🇿', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Metical', 'Gás Natural', 'Cabo Delgado'], 'termos_busca' => ['Mozambique', 'Moçambique', 'Maputo', 'Chapo', 'LNG', 'jihadismo'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'MW', 'nome_pt' => 'Malawi', 'bandeira_emoji' => '🇲🇼', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Kwacha', 'Tabaco', 'FMI'], 'termos_busca' => ['Malawi', 'Lilongwe', 'Chakwera'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'ZM', 'nome_pt' => 'Zâmbia', 'bandeira_emoji' => '🇿🇲', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Kwacha', 'Cobre', 'Dívida'], 'termos_busca' => ['Zambia', 'Zâmbia', 'Lusaka', 'Hichilema', 'cobre'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'ZW', 'nome_pt' => 'Zimbábue', 'bandeira_emoji' => '🇿🇼', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'ZiG', 'Inflação', 'Mineração'], 'termos_busca' => ['Zimbabwe', 'Zimbábue', 'Harare', 'Mnangagwa', 'hiperinflação'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'KM', 'nome_pt' => 'Comores', 'bandeira_emoji' => '🇰🇲', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Franco Comorense', 'Remessas', 'Turismo'], 'termos_busca' => ['Comoros', 'Comores', 'Moroni', 'Azali'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'SC', 'nome_pt' => 'Seychelles', 'bandeira_emoji' => '🇸🇨', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB per capita', 'Rupia SCR', 'Turismo', 'Pesca'], 'termos_busca' => ['Seychelles', 'Vitória', 'Ramkalawan'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'MU', 'nome_pt' => 'Maurício', 'bandeira_emoji' => '🇲🇺', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Rupia MUR', 'Finanças', 'Turismo'], 'termos_busca' => ['Mauritius', 'Maurício', 'Port Louis', 'Ramgoolam'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],

            // África Austral
            ['codigo_pais' => 'ZA', 'nome_pt' => 'África do Sul', 'bandeira_emoji' => '🇿🇦', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Rand', 'Desemprego', 'Mineração'], 'termos_busca' => ['South Africa', 'África do Sul', 'Pretória', 'Ramaphosa', 'ANC', 'BRICS'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'NA', 'nome_pt' => 'Namíbia', 'bandeira_emoji' => '🇳🇦', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Dólar NAD', 'Mineração', 'Hidrogênio Verde'], 'termos_busca' => ['Namibia', 'Namíbia', 'Windhoek', 'Netumbo', 'hidrogênio verde', 'urânio'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'BW', 'nome_pt' => 'Botsuana', 'bandeira_emoji' => '🇧🇼', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Pula', 'Diamantes', 'Bovinos'], 'termos_busca' => ['Botswana', 'Botsuana', 'Gaborone', 'Boko', 'diamantes'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'LS', 'nome_pt' => 'Lesoto', 'bandeira_emoji' => '🇱🇸', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Loti', 'Água', 'Têxteis'], 'termos_busca' => ['Lesotho', 'Lesoto', 'Maseru', 'Majoro'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'SZ', 'nome_pt' => 'Essuatíni', 'bandeira_emoji' => '🇸🇿', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['PIB', 'Lilangeni', 'Têxteis', 'Açúcar'], 'termos_busca' => ['Eswatini', 'Essuatíni', 'Mbabane', 'Rei Mswati'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'AO', 'nome_pt' => 'Angola', 'bandeira_emoji' => '🇦🇴', 'regiao_geopolitica' => 'África', 'indicadores_relevantes' => ['Petróleo', 'PIB', 'Kwanza', 'Dívida'], 'termos_busca' => ['Angola', 'Luanda', 'Lourenço', 'Sonangol', 'petróleo'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],

            // Ásia (Sul e Sudeste)
            ['codigo_pais' => 'IN', 'nome_pt' => 'Índia', 'bandeira_emoji' => '🇮🇳', 'regiao_geopolitica' => 'Ásia', 'indicadores_relevantes' => ['PIB', 'Rúpia', 'CPI', 'FDI'], 'termos_busca' => ['India', 'Índia', 'Nova Delhi', 'Modi', 'RBI', 'SENSEX'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'PK', 'nome_pt' => 'Paquistão', 'bandeira_emoji' => '🇵🇰', 'regiao_geopolitica' => 'Ásia', 'indicadores_relevantes' => ['PIB', 'Rupia', 'Dívida', 'FMI'], 'termos_busca' => ['Pakistan', 'Paquistão', 'Islamabad', 'Sharif', 'exército'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'BD', 'nome_pt' => 'Bangladesh', 'bandeira_emoji' => '🇧🇩', 'regiao_geopolitica' => 'Ásia', 'indicadores_relevantes' => ['PIB', 'Taka', 'Têxteis', 'Remessas'], 'termos_busca' => ['Bangladesh', 'Dhaka', 'Yunus', 'RMG', 'têxteis'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'LK', 'nome_pt' => 'Sri Lanka', 'bandeira_emoji' => '🇱🇰', 'regiao_geopolitica' => 'Ásia', 'indicadores_relevantes' => ['PIB', 'Rupia LKR', 'Turismo', 'Chá'], 'termos_busca' => ['Sri Lanka', 'Colombo', 'Dissanayake', 'crise econômica', 'FMI'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'NP', 'nome_pt' => 'Nepal', 'bandeira_emoji' => '🇳🇵', 'regiao_geopolitica' => 'Ásia', 'indicadores_relevantes' => ['PIB', 'Rupia NPR', 'Remessas', 'Hidroelétrica'], 'termos_busca' => ['Nepal', 'Katmandu', 'Prachanda', 'Himalaia', 'China', 'Índia'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'BT', 'nome_pt' => 'Butão', 'bandeira_emoji' => '🇧🇹', 'regiao_geopolitica' => 'Ásia', 'indicadores_relevantes' => ['PIB', 'Ngultrum', 'Hidroelétrica', 'Felicidade Interna Bruta'], 'termos_busca' => ['Bhutan', 'Butão', 'Thimphu', 'Tobgay', 'Rei Wangchuck'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'MV', 'nome_pt' => 'Maldivas', 'bandeira_emoji' => '🇲🇻', 'regiao_geopolitica' => 'Ásia', 'indicadores_relevantes' => ['PIB', 'Rufiyaa', 'Turismo', 'Mudança Climática'], 'termos_busca' => ['Maldives', 'Maldivas', 'Malé', 'Muizzu', 'China', 'Índia'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'AF', 'nome_pt' => 'Afeganistão', 'bandeira_emoji' => '🇦🇫', 'regiao_geopolitica' => 'Ásia', 'indicadores_relevantes' => ['PIB', 'Afghani', 'Ajuda', 'Taliban'], 'termos_busca' => ['Afghanistan', 'Afeganistão', 'Cabul', 'Taliban', 'Akhundzada'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'MM', 'nome_pt' => 'Myanmar', 'bandeira_emoji' => '🇲🇲', 'regiao_geopolitica' => 'Ásia', 'indicadores_relevantes' => ['PIB', 'Kyat', 'Junta', 'Sanções'], 'termos_busca' => ['Myanmar', 'Birmânia', 'Naypyidaw', 'Min Aung Hlaing', 'golpe', 'NLD'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'TH', 'nome_pt' => 'Tailândia', 'bandeira_emoji' => '🇹🇭', 'regiao_geopolitica' => 'Ásia', 'indicadores_relevantes' => ['PIB', 'Baht', 'Turismo', 'Exportações'], 'termos_busca' => ['Thailand', 'Tailândia', 'Bangkok', 'Paetongtarn', 'Rei Vajiralongkorn'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'VN', 'nome_pt' => 'Vietnã', 'bandeira_emoji' => '🇻🇳', 'regiao_geopolitica' => 'Ásia', 'indicadores_relevantes' => ['PIB', 'Dong', 'Exportações', 'FDI'], 'termos_busca' => ['Vietnam', 'Vietnã', 'Hanói', 'To Lam', 'Samsung', 'exportações'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'KH', 'nome_pt' => 'Camboja', 'bandeira_emoji' => '🇰🇭', 'regiao_geopolitica' => 'Ásia', 'indicadores_relevantes' => ['PIB', 'Riel', 'Têxteis', 'China'], 'termos_busca' => ['Cambodia', 'Camboja', 'Phnom Penh', 'Hun Manet', 'China'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'LA', 'nome_pt' => 'Laos', 'bandeira_emoji' => '🇱🇦', 'regiao_geopolitica' => 'Ásia', 'indicadores_relevantes' => ['PIB', 'Kip', 'Dívida', 'China'], 'termos_busca' => ['Laos', 'Vientiane', 'Sonexay', 'trem China-Laos', 'dívida'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'MY', 'nome_pt' => 'Malásia', 'bandeira_emoji' => '🇲🇾', 'regiao_geopolitica' => 'Ásia', 'indicadores_relevantes' => ['PIB', 'Ringgit', 'Semicondutores', 'Exportações'], 'termos_busca' => ['Malaysia', 'Malásia', 'Kuala Lumpur', 'Anwar Ibrahim', 'ASEAN'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'SG', 'nome_pt' => 'Singapura', 'bandeira_emoji' => '🇸🇬', 'regiao_geopolitica' => 'Ásia', 'indicadores_relevantes' => ['PIB', 'Dólar SGD', 'Comércio', 'Finanças'], 'termos_busca' => ['Singapore', 'Singapura', 'Lawrence Wong', 'hub financeiro', 'ASEAN'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'ID', 'nome_pt' => 'Indonésia', 'bandeira_emoji' => '🇮🇩', 'regiao_geopolitica' => 'Ásia', 'indicadores_relevantes' => ['PIB', 'Rupiah', 'Níquel', 'Commodities'], 'termos_busca' => ['Indonesia', 'Indonésia', 'Jacarta', 'Prabowo', 'ASEAN', 'níquel'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'PH', 'nome_pt' => 'Filipinas', 'bandeira_emoji' => '🇵🇭', 'regiao_geopolitica' => 'Ásia', 'indicadores_relevantes' => ['PIB', 'Peso PHP', 'Remessas', 'Mar do Sul da China'], 'termos_busca' => ['Philippines', 'Filipinas', 'Manila', 'Marcos', 'Mar do Sul da China', 'BPO'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'TL', 'nome_pt' => 'Timor-Leste', 'bandeira_emoji' => '🇹🇱', 'regiao_geopolitica' => 'Ásia', 'indicadores_relevantes' => ['PIB', 'Dólar', 'Petróleo', 'Fundo Petrolífero'], 'termos_busca' => ['Timor-Leste', 'Díli', 'Gusmão', 'petróleo'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'BN', 'nome_pt' => 'Brunei', 'bandeira_emoji' => '🇧🇳', 'regiao_geopolitica' => 'Ásia', 'indicadores_relevantes' => ['PIB per capita', 'Dólar BND', 'Petróleo', 'Gás'], 'termos_busca' => ['Brunei', 'Bandar Seri Begawan', 'Sultão Bolkiah', 'petróleo'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],

            // Ásia Oriental
            ['codigo_pais' => 'CN', 'nome_pt' => 'China', 'bandeira_emoji' => '🇨🇳', 'regiao_geopolitica' => 'Ásia', 'indicadores_relevantes' => ['PIB', 'Balança Comercial', 'Yuan', 'CPI'], 'termos_busca' => ['China', 'Pequim', 'Xi Jinping', 'PCC', 'PBOC'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'JP', 'nome_pt' => 'Japão', 'bandeira_emoji' => '🇯🇵', 'regiao_geopolitica' => 'Ásia', 'indicadores_relevantes' => ['PIB', 'Iene', 'Dívida/PIB', 'BoJ Rate'], 'termos_busca' => ['Japan', 'Japão', 'Tóquio', 'Ishiba', 'BoJ', 'Nikkei'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'KR', 'nome_pt' => 'Coreia do Sul', 'bandeira_emoji' => '🇰🇷', 'regiao_geopolitica' => 'Ásia', 'indicadores_relevantes' => ['PIB', 'Won', 'KOSPI', 'Semicondutores'], 'termos_busca' => ['South Korea', 'Coreia do Sul', 'Seul', 'Lee Jae-myung', 'Samsung', 'TSMC'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'KP', 'nome_pt' => 'Coreia do Norte', 'bandeira_emoji' => '🇰🇵', 'regiao_geopolitica' => 'Ásia', 'indicadores_relevantes' => ['Mísseis', 'Sanções', 'Carvão'], 'termos_busca' => ['North Korea', 'Coreia do Norte', 'Kim Jong-un', 'DPRK', 'míssil'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'MN', 'nome_pt' => 'Mongólia', 'bandeira_emoji' => '🇲🇳', 'regiao_geopolitica' => 'Ásia', 'indicadores_relevantes' => ['PIB', 'Tugrik', 'Carvão', 'Cobre'], 'termos_busca' => ['Mongolia', 'Mongólia', 'Ulan Bator', 'Oyun-Erdene', 'carvão', 'China'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'TW', 'nome_pt' => 'Taiwan', 'bandeira_emoji' => '🇹🇼', 'regiao_geopolitica' => 'Ásia', 'indicadores_relevantes' => ['PIB', 'Dólar TWD', 'Semicondutores', 'TSMC'], 'termos_busca' => ['Taiwan', 'Taipei', 'Lai Ching-te', 'TSMC', 'China', 'semicondutores', 'estreito de Taiwan'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],

            // Oceania
            ['codigo_pais' => 'AU', 'nome_pt' => 'Austrália', 'bandeira_emoji' => '🇦🇺', 'regiao_geopolitica' => 'Oceania', 'indicadores_relevantes' => ['PIB', 'Dólar AUD', 'Minério de Ferro', 'RBA Rate'], 'termos_busca' => ['Australia', 'Austrália', 'Camberra', 'Albanese', 'RBA', 'China'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'NZ', 'nome_pt' => 'Nova Zelândia', 'bandeira_emoji' => '🇳🇿', 'regiao_geopolitica' => 'Oceania', 'indicadores_relevantes' => ['PIB', 'Dólar NZD', 'Laticínios', 'RBNZ Rate'], 'termos_busca' => ['New Zealand', 'Nova Zelândia', 'Wellington', 'Luxon', 'RBNZ'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'FJ', 'nome_pt' => 'Fiji', 'bandeira_emoji' => '🇫🇯', 'regiao_geopolitica' => 'Oceania', 'indicadores_relevantes' => ['PIB', 'Dólar FJD', 'Turismo', 'Açúcar'], 'termos_busca' => ['Fiji', 'Suva', 'Rabuka', 'turismo'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'PG', 'nome_pt' => 'Papua-Nova Guiné', 'bandeira_emoji' => '🇵🇬', 'regiao_geopolitica' => 'Oceania', 'indicadores_relevantes' => ['PIB', 'Kina', 'GNL', 'Ouro'], 'termos_busca' => ['Papua New Guinea', 'Papua-Nova Guiné', 'Port Moresby', 'Marape', 'GNL'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'SB', 'nome_pt' => 'Ilhas Salomão', 'bandeira_emoji' => '🇸🇧', 'regiao_geopolitica' => 'Oceania', 'indicadores_relevantes' => ['PIB', 'Dólar SBD', 'Madeira', 'China'], 'termos_busca' => ['Solomon Islands', 'Ilhas Salomão', 'Honiara', 'Sogavare', 'China'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'VU', 'nome_pt' => 'Vanuatu', 'bandeira_emoji' => '🇻🇺', 'regiao_geopolitica' => 'Oceania', 'indicadores_relevantes' => ['PIB', 'Vatu', 'Turismo', 'Agricultura'], 'termos_busca' => ['Vanuatu', 'Port Vila', 'Natapei'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'WS', 'nome_pt' => 'Samoa', 'bandeira_emoji' => '🇼🇸', 'regiao_geopolitica' => 'Oceania', 'indicadores_relevantes' => ['PIB', 'Tala', 'Remessas', 'Turismo'], 'termos_busca' => ['Samoa', 'Apia', 'Fiame'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'TO', 'nome_pt' => 'Tonga', 'bandeira_emoji' => '🇹🇴', 'regiao_geopolitica' => 'Oceania', 'indicadores_relevantes' => ['PIB', 'Paanga', 'Remessas', 'Turismo'], 'termos_busca' => ['Tonga', "Nuku'alofa", 'Siaosi Taufa'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'KI', 'nome_pt' => 'Kiribati', 'bandeira_emoji' => '🇰🇮', 'regiao_geopolitica' => 'Oceania', 'indicadores_relevantes' => ['PIB', 'Dólar AUD', 'Mudança Climática', 'Pesca'], 'termos_busca' => ['Kiribati', 'Tarawa', 'Maamau', 'mudança climática', 'China'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'FM', 'nome_pt' => 'Micronésia', 'bandeira_emoji' => '🇫🇲', 'regiao_geopolitica' => 'Oceania', 'indicadores_relevantes' => ['PIB', 'Dólar USD', 'Ajuda EUA', 'Pesca'], 'termos_busca' => ['Micronesia', 'Micronésia', 'Palikir', 'Simina', 'EUA'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'MH', 'nome_pt' => 'Ilhas Marshall', 'bandeira_emoji' => '🇲🇭', 'regiao_geopolitica' => 'Oceania', 'indicadores_relevantes' => ['PIB', 'Dólar USD', 'Ajuda', 'Pesca'], 'termos_busca' => ['Marshall Islands', 'Ilhas Marshall', 'Majuro', 'Heine'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'PW', 'nome_pt' => 'Palau', 'bandeira_emoji' => '🇵🇼', 'regiao_geopolitica' => 'Oceania', 'indicadores_relevantes' => ['PIB', 'Dólar USD', 'Turismo', 'Pesca'], 'termos_busca' => ['Palau', 'Ngerulmud', 'Whipps', 'Taiwan', 'turismo'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'NR', 'nome_pt' => 'Nauru', 'bandeira_emoji' => '🇳🇷', 'regiao_geopolitica' => 'Oceania', 'indicadores_relevantes' => ['PIB', 'Dólar AUD', 'Fosfato', 'Ajuda'], 'termos_busca' => ['Nauru', 'Yaren', 'Waqa'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
            ['codigo_pais' => 'TV', 'nome_pt' => 'Tuvalu', 'bandeira_emoji' => '🇹🇻', 'regiao_geopolitica' => 'Oceania', 'indicadores_relevantes' => ['PIB', 'Dólar AUD', 'Mudança Climática', 'Domínio .tv'], 'termos_busca' => ['Tuvalu', 'Funafuti', 'Feleti', 'mudança climática', 'afundamento'], 'contexto_geopolitico' => null, 'analise_lideranca' => null, 'gerado_em' => null],
        ];

        foreach ($paises as $dados) {
            PerfilPais::updateOrCreate(
                ['codigo_pais' => $dados['codigo_pais']],
                $dados
            );
        }
    }
}
