<?php

namespace Database\Seeders;

use App\Models\PerfilPais;
use Illuminate\Database\Seeder;

class PaisesInicialSeeder extends Seeder
{
    public function run(): void
    {
        $paises = [
            [
                'codigo_pais'          => 'US',
                'nome_pt'              => 'Estados Unidos',
                'bandeira_emoji'       => '🇺🇸',
                'regiao_geopolitica'   => 'América do Norte',
                'indicadores_relevantes' => ['PIB', 'Fed Rate', 'Dívida/PIB', 'CPI'],
                'termos_busca'         => ['United States', 'EUA', 'Washington', 'Fed', 'Trump'],
                'contexto_geopolitico' => null,
                'analise_lideranca'    => null,
                'gerado_em'            => null,
            ],
            [
                'codigo_pais'          => 'CN',
                'nome_pt'              => 'China',
                'bandeira_emoji'       => '🇨🇳',
                'regiao_geopolitica'   => 'Ásia-Pacífico',
                'indicadores_relevantes' => ['PIB', 'Balança Comercial', 'Yuan', 'CPI'],
                'termos_busca'         => ['China', 'Pequim', 'Xi Jinping', 'PCC'],
                'contexto_geopolitico' => null,
                'analise_lideranca'    => null,
                'gerado_em'            => null,
            ],
            [
                'codigo_pais'          => 'RU',
                'nome_pt'              => 'Rússia',
                'bandeira_emoji'       => '🇷🇺',
                'regiao_geopolitica'   => 'Europa Oriental',
                'indicadores_relevantes' => ['PIB', 'Rublo', 'Petróleo', 'Reservas'],
                'termos_busca'         => ['Russia', 'Moscou', 'Putin', 'Kremlin'],
                'contexto_geopolitico' => null,
                'analise_lideranca'    => null,
                'gerado_em'            => null,
            ],
            [
                'codigo_pais'          => 'DE',
                'nome_pt'              => 'Alemanha',
                'bandeira_emoji'       => '🇩🇪',
                'regiao_geopolitica'   => 'Europa Ocidental',
                'indicadores_relevantes' => ['PIB', 'IPC', 'Exportações', 'PMI'],
                'termos_busca'         => ['Alemanha', 'Berlim', 'Bundesbank', 'DAX'],
                'contexto_geopolitico' => null,
                'analise_lideranca'    => null,
                'gerado_em'            => null,
            ],
            [
                'codigo_pais'          => 'JP',
                'nome_pt'              => 'Japão',
                'bandeira_emoji'       => '🇯🇵',
                'regiao_geopolitica'   => 'Ásia-Pacífico',
                'indicadores_relevantes' => ['PIB', 'Iene', 'Dívida/PIB', 'BoJ Rate'],
                'termos_busca'         => ['Japan', 'Japão', 'Tóquio', 'Kishida', 'BoJ'],
                'contexto_geopolitico' => null,
                'analise_lideranca'    => null,
                'gerado_em'            => null,
            ],
            [
                'codigo_pais'          => 'GB',
                'nome_pt'              => 'Reino Unido',
                'bandeira_emoji'       => '🇬🇧',
                'regiao_geopolitica'   => 'Europa Ocidental',
                'indicadores_relevantes' => ['PIB', 'Libra', 'CPI', 'BoE Rate'],
                'termos_busca'         => ['United Kingdom', 'Reino Unido', 'Londres', 'BoE'],
                'contexto_geopolitico' => null,
                'analise_lideranca'    => null,
                'gerado_em'            => null,
            ],
            [
                'codigo_pais'          => 'FR',
                'nome_pt'              => 'França',
                'bandeira_emoji'       => '🇫🇷',
                'regiao_geopolitica'   => 'Europa Ocidental',
                'indicadores_relevantes' => ['PIB', 'CPI', 'Exportações', 'CAC 40'],
                'termos_busca'         => ['France', 'França', 'Paris', 'Macron', 'Élysée'],
                'contexto_geopolitico' => null,
                'analise_lideranca'    => null,
                'gerado_em'            => null,
            ],
            [
                'codigo_pais'          => 'SA',
                'nome_pt'              => 'Arábia Saudita',
                'bandeira_emoji'       => '🇸🇦',
                'regiao_geopolitica'   => 'Oriente Médio',
                'indicadores_relevantes' => ['Petróleo', 'PIB', 'Reservas', 'OPEC'],
                'termos_busca'         => ['Saudi Arabia', 'Arábia Saudita', 'Riad', 'MBS', 'Aramco'],
                'contexto_geopolitico' => null,
                'analise_lideranca'    => null,
                'gerado_em'            => null,
            ],
            [
                'codigo_pais'          => 'IR',
                'nome_pt'              => 'Irã',
                'bandeira_emoji'       => '🇮🇷',
                'regiao_geopolitica'   => 'Oriente Médio',
                'indicadores_relevantes' => ['Petróleo', 'Inflação', 'Rial', 'Sanções'],
                'termos_busca'         => ['Iran', 'Irã', 'Teerã', 'Khamenei', 'IRGC'],
                'contexto_geopolitico' => null,
                'analise_lideranca'    => null,
                'gerado_em'            => null,
            ],
            [
                'codigo_pais'          => 'IL',
                'nome_pt'              => 'Israel',
                'bandeira_emoji'       => '🇮🇱',
                'regiao_geopolitica'   => 'Oriente Médio',
                'indicadores_relevantes' => ['PIB', 'Shekel', 'Déficit', 'CPI'],
                'termos_busca'         => ['Israel', 'Tel Aviv', 'Netanyahu', 'IDF', 'Gaza'],
                'contexto_geopolitico' => null,
                'analise_lideranca'    => null,
                'gerado_em'            => null,
            ],
            [
                'codigo_pais'          => 'IN',
                'nome_pt'              => 'Índia',
                'bandeira_emoji'       => '🇮🇳',
                'regiao_geopolitica'   => 'Ásia-Pacífico',
                'indicadores_relevantes' => ['PIB', 'Rúpia', 'CPI', 'FDI'],
                'termos_busca'         => ['India', 'Índia', 'Nova Delhi', 'Modi', 'RBI'],
                'contexto_geopolitico' => null,
                'analise_lideranca'    => null,
                'gerado_em'            => null,
            ],
            [
                'codigo_pais'          => 'BR',
                'nome_pt'              => 'Brasil',
                'bandeira_emoji'       => '🇧🇷',
                'regiao_geopolitica'   => 'América do Sul',
                'indicadores_relevantes' => ['PIB', 'Selic', 'IPCA', 'Câmbio'],
                'termos_busca'         => ['Brasil', 'Brasília', 'Lula', 'Banco Central', 'IPCA'],
                'contexto_geopolitico' => null,
                'analise_lideranca'    => null,
                'gerado_em'            => null,
            ],
            [
                'codigo_pais'          => 'TR',
                'nome_pt'              => 'Turquia',
                'bandeira_emoji'       => '🇹🇷',
                'regiao_geopolitica'   => 'Eurásia',
                'indicadores_relevantes' => ['Lira', 'Inflação', 'PIB', 'Juro TCMB'],
                'termos_busca'         => ['Turkey', 'Turquia', 'Ancara', 'Erdogan', 'TCMB'],
                'contexto_geopolitico' => null,
                'analise_lideranca'    => null,
                'gerado_em'            => null,
            ],
            [
                'codigo_pais'          => 'PK',
                'nome_pt'              => 'Paquistão',
                'bandeira_emoji'       => '🇵🇰',
                'regiao_geopolitica'   => 'Ásia-Pacífico',
                'indicadores_relevantes' => ['PIB', 'Rupia', 'Dívida', 'FMI'],
                'termos_busca'         => ['Pakistan', 'Paquistão', 'Islamabad', 'ISI', 'exército'],
                'contexto_geopolitico' => null,
                'analise_lideranca'    => null,
                'gerado_em'            => null,
            ],
            [
                'codigo_pais'          => 'KP',
                'nome_pt'              => 'Coreia do Norte',
                'bandeira_emoji'       => '🇰🇵',
                'regiao_geopolitica'   => 'Ásia-Pacífico',
                'indicadores_relevantes' => ['Mísseis', 'Sanções', 'Carvão'],
                'termos_busca'         => ['North Korea', 'Coreia do Norte', 'Kim Jong-un', 'DPRK', 'míssil'],
                'contexto_geopolitico' => null,
                'analise_lideranca'    => null,
                'gerado_em'            => null,
            ],
            [
                'codigo_pais'          => 'UA',
                'nome_pt'              => 'Ucrânia',
                'bandeira_emoji'       => '🇺🇦',
                'regiao_geopolitica'   => 'Europa Oriental',
                'indicadores_relevantes' => ['PIB', 'Hryvnia', 'Dívida', 'Reconstrução'],
                'termos_busca'         => ['Ukraine', 'Ucrânia', 'Kiev', 'Zelensky', 'guerra'],
                'contexto_geopolitico' => null,
                'analise_lideranca'    => null,
                'gerado_em'            => null,
            ],
            [
                'codigo_pais'          => 'VE',
                'nome_pt'              => 'Venezuela',
                'bandeira_emoji'       => '🇻🇪',
                'regiao_geopolitica'   => 'América do Sul',
                'indicadores_relevantes' => ['Petróleo', 'Inflação', 'Bolívar', 'Sanções'],
                'termos_busca'         => ['Venezuela', 'Caracas', 'Maduro', 'PDVSA', 'petróleo'],
                'contexto_geopolitico' => null,
                'analise_lideranca'    => null,
                'gerado_em'            => null,
            ],
            [
                'codigo_pais'          => 'NG',
                'nome_pt'              => 'Nigéria',
                'bandeira_emoji'       => '🇳🇬',
                'regiao_geopolitica'   => 'África',
                'indicadores_relevantes' => ['PIB', 'Naira', 'Petróleo', 'Inflação'],
                'termos_busca'         => ['Nigeria', 'Nigéria', 'Abuja', 'Tinubu', 'NNPC'],
                'contexto_geopolitico' => null,
                'analise_lideranca'    => null,
                'gerado_em'            => null,
            ],
            [
                'codigo_pais'          => 'MX',
                'nome_pt'              => 'México',
                'bandeira_emoji'       => '🇲🇽',
                'regiao_geopolitica'   => 'América do Norte',
                'indicadores_relevantes' => ['PIB', 'Peso', 'Remessas', 'Nearshoring'],
                'termos_busca'         => ['Mexico', 'México', 'CDMX', 'Sheinbaum', 'Banxico'],
                'contexto_geopolitico' => null,
                'analise_lideranca'    => null,
                'gerado_em'            => null,
            ],
            [
                'codigo_pais'          => 'AR',
                'nome_pt'              => 'Argentina',
                'bandeira_emoji'       => '🇦🇷',
                'regiao_geopolitica'   => 'América do Sul',
                'indicadores_relevantes' => ['PIB', 'Peso', 'Inflação', 'FMI', 'Reservas'],
                'termos_busca'         => ['Argentina', 'Buenos Aires', 'Milei', 'BCRA', 'dólar'],
                'contexto_geopolitico' => null,
                'analise_lideranca'    => null,
                'gerado_em'            => null,
            ],
        ];

        foreach ($paises as $dados) {
            PerfilPais::updateOrCreate(
                ['codigo_pais' => $dados['codigo_pais']],
                $dados
            );
        }
    }
}
